### ISSUE TITLE
[feature]建议跟进v2ray HTTP2不强制使用tls的改进

### ISSUE THREAD

**Issue by ycycorona** [sprov065/v2-ui#101]
**提问须知**

**描述你想要的功能**
当前如果选择http2模式，表单会强制要求填写tls参数，而事实上很多时候tls已经在外部网络层设置了（比如使用nginx时），所以这里是不是可以不要强制要求使用tls.

**为何需要此功能**
### 引用v2ray文档原文
"V2Ray 4.20 中对服务端的TLS配置的强制条件移除，为了在特殊用途的分流部署环境中，由外部网关组件完成TLS层对话，V2Ray作为后端应用，网关和V2Ray间使用称为h2c的明文http/2进行通讯。"
(https://www.v2ray.com/chapter_02/transport/h2.html)
**其它说明**

**Comment by sprov065** [comment]
可以跟进
