### ISSUE TITLE
[feature]添加docker部署

### ISSUE THREAD

**Issue by danerlt** [sprov065/v2-ui#102]
**提问须知**
希望能支持docker部署

**描述你想要的功能**
希望能支持docker部署

**为何需要此功能**
使用docker部署,只需要一条命令就ok了,现在还需要配置手动配置nginx感觉有点麻烦

**其它说明**

**Comment by sprov065** [comment]
现在的安装难道不是一条命令吗，nginx 是不会帮你自动配置的，必须要自己配，就算用 docker 你也要自己配
