### ISSUE TITLE
[BUG] 配置 https 访问 出现空白

### ISSUE THREAD

**Issue by Twor** [sprov065/v2-ui#103]
**描述问题**
> 
![2019-10-15-070118_1920x1080_scrot](https://user-images.githubusercontent.com/18731946/66788306-b320c180-ef19-11e9-8dbd-15996d47b98e.png)

**面板是否正常运行**
> ➜  ~ systemctl status v2-ui -l
● v2-ui.service - v2-ui Service
   Loaded: loaded (/etc/systemd/system/v2-ui.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2019-10-15 06:34:20 CST; 7min ago
 Main PID: 13289 (v2-ui)
   CGroup: /system.slice/v2-ui.service
           ├─13289 /usr/local/v2-ui/v2-ui
           └─13290 /usr/local/v2-ui/v2-ui

**与问题相关的面板日志及其他内容**
> cat /etc/v2-ui/v2-ui.log (日志文件为空)

**所使用的面板版本**
> 当前面板版本 | 4.7.0

**所使用的系统（服务器）**
centos 7+ 
Linux twor.me 5.3.6-1.el7.elrepo.x86_64 #1 SMP Fri Oct 11 17:24:39 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux

**所使用的浏览器**
chromium

**你猜测可能的原因**
> 我的nginx配置不对?

**Comment by sprov065** [comment]
是配置不对，面板配置了 https，nginx 反代又写 http
