### ISSUE TITLE
[BUG]不能用v2ray在学校网

### ISSUE THREAD

**Issue by Shafqat905** [sprov065/v2-ui#106]
V2ray用得很好但是我去上课的时候不能用v2ray在学校网我试了TCP ，kcp 都不能用

**Comment by sprov065** [comment]
我佛了，你学校网有问题问我干啥

**Comment by Shafqat905** [comment]
我学校网没有问题就是vpn不能用
以前我用shadow socks 现在V2Ray 用不了

**Comment by narakuzi** [comment]
那就换成ss协议啊,又不是只有v2ray,你这问题应该去问v2ray作者为什么校园网不能用
