### ISSUE TITLE
[other]DO的英国路线centos7.6  x64 搭建错误 换了乌班图同一错误

### ISSUE THREAD

**Issue by yuzhenghuan** [sprov065/v2-ui#109]
开始安装
Reading package lists... Done
Building dependency tree       
Reading state information... Done
curl is already the newest version (7.47.0-1ubuntu2.14).
tar is already the newest version (1.28-2.1ubuntu0.1).
wget is already the newest version (1.17.1-1ubuntu1.5).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
开始安装or升级v2ray
/dev/fd/62: line 1: syntax error near unexpected token `newline'
/dev/fd/62: line 1: `<!DOCTYPE html>'
v2ray安装或升级失败，请检查错误信

**Comment by sprov065** [comment]
这是 v2ray 官方安装脚本的问题，我的脚本只是调用了 v2ray 官方脚本进行安装
