### ISSUE TITLE
[other] 安装时提示证书问题 

### ISSUE THREAD

**Issue by WardLiu** [sprov065/v2-ui#111]
Reading package lists... Done
Building dependency tree       
Reading state information... Done
curl is already the newest version (7.52.1-5+deb9u9).
tar is already the newest version (1.29b-1.1).
wget is already the newest version (1.18-5+deb9u3).
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
开始安装or升级v2ray
Installing V2Ray v4.20.0 on x86_64
Downloading V2Ray: https://github.com/v2ray/v2ray-core/releases/download/v4.20.0/v2ray-linux-64.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   608    0   608    0     0   1214      0 --:--:-- --:--:-- --:--:--  1216
  0     0    0     0    0     0      0      0 --:--:--  0:00:08 --:--:--     0curl: (6) Could not resolve host: github-production-release-asset-2e65be.s3.amazonaws.com
Failed to download! Please check your network or try again.
v2ray安装或升级失败，请检查错误信息

**Comment by sprov065** [comment]
可能是自身服务器的 DNS 问题：

Could not resolve host: github-production-release-asset-2e65be.s3.amazonaws.com
