### ISSUE TITLE
[feature]同一端口多用户

### ISSUE THREAD

**Issue by shanrenxj** [sprov065/v2-ui#113]
**描述你想要的功能**
同一端口支持多用户配置

**为何需要此功能**
CDN只支持443端口加速，其他端口加速不了

**其它说明**
github上面的multi-v2ray脚本支持同一端口多用户，但是还有不少bug，使用也没v2-ui方便

**Comment by sprov065** [comment]
重复问题

**Comment by shinelinxx** [comment]
> **描述你想要的功能**
> 同一端口支持多用户配置
> 
> **为何需要此功能**
> CDN只支持443端口加速，其他端口加速不了
> 
> **其它说明**
> github上面的multi-v2ray脚本支持同一端口多用户，但是还有不少bug，使用也没v2-ui方便

监听443端口，使用nginx反向代理，配置不同的location(ws path)来转发到不同的端口。

**Comment by Leocn** [comment]
用v2-ui做tsl+ws配置时，不能直接把连接导入到客户端使用，需要手动调整。
另外还需要配置nginx文件。
思路就是shinelinxx。
