### ISSUE TITLE
[feature]希望作者大大补充…

### ISSUE THREAD

**Issue by SkyFuInMC** [sprov065/v2-ui#116]
## 需要添加的特性
1. Outbound管理。
2. 路由管理。

## 为什么要添加
1. 如果服务器要作为中转服务器的话，添加Outbound管理能够简化配置中转的流程。（比如服务器端中转VMess、Shadowsocks和SOCKS流量）
2. 简化配置对不同流量采取的不同行为。

## 其他
如果添加，感激不尽！

**Comment by sprov065** [comment]
这个就太麻烦了，大部分人都用不到，可以自己在配置模板自由发挥
