### ISSUE TITLE
[other]请问v2ray程序的的日志在哪里?请问api的接口可以简单说一下吗?

### ISSUE THREAD

**Issue by sllzwsgdsg** [sprov065/v2-ui#118]
1. 请问v2ray的程序日志在哪儿? 想看哪个用户连接以后的相关日志.
2. 请问v2-ui面板有对外的api接口吗? 比如对用户的增删改查操作, 想通过自己写的后台连接您的v2-ui面板.
3. 希望能增加用户账号的生效时间的字段, 比如某个用户只有1天有效期. 目前在v2-ui面板内没地方可以设置. 
以上.

**Comment by sprov065** [comment]
看v2ray官方文档
没有
不会增加这个功能
