### ISSUE TITLE
使用百度云CDN出现521 Origin Down错误[other]

### ISSUE THREAD

**Issue by 2Kil** [sprov065/v2-ui#121]
![1](https://user-images.githubusercontent.com/25128763/68012768-eeffa900-fcc5-11e9-9507-baa253d206c5.jpg)
![2](https://user-images.githubusercontent.com/25128763/68012769-eeffa900-fcc5-11e9-9245-1a2a4d398845.jpg)
百度证书已经部署好了

**Comment by 2Kil** [comment]
是需要手动配置nginx或者Apache吗?

**Comment by sprov065** [comment]
v2ray + ws 又不是一个网站，当然不能在浏览器访问，百度云是否支持 websocket 我不清楚，我记得百度云的 https 是要钱的，这些问题是你自己要解决的，v2ray 和面板本身没有问题
