### ISSUE TITLE
[BUG]新建谷歌云VM 默认安装5.0新版本，添加账号无法运行

### ISSUE THREAD

**Issue by Everwishing** [sprov065/v2-ui#123]
# 提问须知
 - 先仔细阅读博客文章及评论，查看是否有相关问题和解决方案，再查看所有 issues，包括已开启的和已关闭的，确认没有任何地方可以解决你的问题时再提问。
 - 如果是 v2ray 本身的问题，请找 v2ray 官方，而不是在这里问。
 - 如果是你自身的技术知识积累不够，例如 xxx 不会配置，xx 软件不会用，配置错误导致连不上等等问题。你可以换一个提问模板进行提问，而不是 BUG 反馈模板。此类问题我一般不会做回答，除非是有意义的问题。建议多学习相关技术，积累自身的技术水平。
 - 如果需要上传图片，直接将图片拖入此文本框即可。
 - 提问的艺术：https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md

**描述你的问题**
>默认新建一个谷歌云VM，默认安装5.0.1版本，面板随便添加账号后，v2ray状态 显示出错，删除账号就运行正常。相同操作在搬W工上，正常！。

**面板是否正常运行**
>提示：systemctl status v2-ui -l
正常
root@ssrv2ray:~# cat /etc/v2-ui/v2-ui.log
root@ssrv2ray:~# systemctl status v2-ui -l
● v2-ui.service - v2-ui Service
   Loaded: loaded (/etc/systemd/system/v2-ui.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2019-11-06 10:59:49 CST; 12min ago
 Main PID: 19653 (v2-ui)
    Tasks: 3 (limit: 4915)
   CGroup: /system.slice/v2-ui.service
           ├─19653 /usr/local/v2-ui/v2-ui
           └─19657 /usr/local/v2-ui/v2-ui

Nov 06 10:59:49 ssrv2ray systemd[1]: Started v2-ui Service.

**与问题相关的面板日志及其他内容**
>提示：cat /etc/v2-ui/v2-ui.log
没有东西出来，搬工的也没有

**你所使用的面板版本**5.0.1

**你所使用的系统（服务器）**谷歌云

**你所使用的浏览器**google

**你猜测可能的原因**谷歌云设置问题？

**Comment by sprov065** [comment]
添加一个账号就出错，删除账号就正常，那说明是这个账号的问题，你很可能给这个账号配置了错误的内容

**Comment by Everwishing** [comment]
不是就基本的名字（英文字母）和vps所在的IP。其它并未配置，保存10秒后运行状态就报错误！再复杂的配置 ，在搬W工上的VPS是正常的。因为出现这个问题，谷歌云上的VM也是全新新建，完全无其它设置，v2-ui也是默认安装后第一步的测试。不知还出在哪方面？

**Comment by sprov065** [comment]
不需要填监听IP，默认就行

**Comment by Everwishing** [comment]
确实如上所说。IP项不需要手动设置。0.0.0.0 自动填入了域名。谢谢解答！
