### ISSUE TITLE
我发现使用TLS的服务在客户端不需要填写域名，或者填错的域名也不影响

### ISSUE THREAD

**Issue by fengjiangz** [sprov065/v2-ui#124]
不知道这是v2ray本身的问题还是v2-ui的问题，客户端不需要填写域名，或者填错的域名也不影响连接。
我试了别人的TLS+WS服务，不填域名也可以正常连接，但填错的域名不可以。

**Comment by sprov065** [comment]
这是v2ray的机制，如果觉得不合理去找v2ray

**Comment by fengjiangz** [comment]
> 这是v2ray的机制，如果觉得不合理去找v2ray

不不不，重点是第二问。我觉得是v2-ui输出的配置文件有错误

**Comment by sprov065** [comment]
> > 这是v2ray的机制，如果觉得不合理去找v2ray
> 
> 不不不，重点是第二问。我觉得是v2-ui输出的配置文件有错误

有错误那你就直接贴出来嘛，配上 v2ray 官方文档的依据，还有自己的实际测试，不要这么绕
