### ISSUE TITLE
通过v2-ui配置无法访问局域网内其他主机

### ISSUE THREAD

**Issue by shoushi01** [sprov065/v2-ui#125]
我的服务器架设在NAT后，通过端口映射提供服务。而通过v2-ui配置默认包含了屏蔽局域网内连接的选项，即使通过手动修改配置文件，下次v2-ui重启时也会被刷新覆盖。不知作者可否将blackhole作为可选项而非必选项？

**Comment by sprov065** [comment]
自己修改配置模板
