### ISSUE TITLE
[BUG]Debain9 安装v2-ui启动失败

### ISSUE THREAD

**Issue by icemanstudy** [sprov065/v2-ui#127]
Created symlink /etc/systemd/system/multi-user.target.wants/v2-ui.service → /etc                                                                           /systemd/system/v2-ui.service.
v2-ui v5.0.1 安装完成，面板已启动，

如果是全新安装，默认网页端口为 65432，用户名和密码默认都是 admin
请自行确保此端口没有被其他程序占用，并且确保 65432 端口已放行

如果是更新面板，则按你之前的方式访问面板

v2-ui 管理脚本使用方法:
----------------------------------------------
v2-ui              - 显示管理菜单 (功能更多)
v2-ui start        - 启动 v2-ui 面板
v2-ui stop         - 停止 v2-ui 面板
v2-ui restart      - 重启 v2-ui 面板
v2-ui status       - 查看 v2-ui 状态
v2-ui enable       - 设置 v2-ui 开机自启
v2-ui disable      - 取消 v2-ui 开机自启
v2-ui log          - 查看 v2-ui 日志
v2-ui update       - 更新 v2-ui 面板
v2-ui install      - 安装 v2-ui 面板
v2-ui uninstall    - 卸载 v2-ui 面板
----------------------------------------------
root@iceman:~# v2-ui status
● v2-ui.service - v2-ui Service
   Loaded: loaded (/etc/systemd/system/v2-ui.service; enabled; vendor preset: en
   Active: failed (Result: exit-code) since Wed 2019-11-06 20:37:11 EST; 1min 0s
  Process: 10219 ExecStart=/usr/local/v2-ui/v2-ui (code=exited, status=203/EXEC)
 Main PID: 10219 (code=exited, status=203/EXEC)

Nov 06 20:37:11 iceman systemd[1]: Started v2-ui Service.
Nov 06 20:37:11 iceman systemd[10219]: v2-ui.service: Failed at step EXEC spawni
Nov 06 20:37:11 iceman systemd[1]: v2-ui.service: Main process exited, code=exit
Nov 06 20:37:11 iceman systemd[1]: v2-ui.service: Unit entered failed state.
Nov 06 20:37:11 iceman systemd[1]: v2-ui.service: Failed with result 'exit-code'
lines 1-11/11 (END)...skipping...
● v2-ui.service - v2-ui Service
   Loaded: loaded (/etc/systemd/system/v2-ui.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2019-11-06 20:37:11 EST; 1min 0s ago
  Process: 10219 ExecStart=/usr/local/v2-ui/v2-ui (code=exited, status=203/EXEC)
 Main PID: 10219 (code=exited, status=203/EXEC)

Nov 06 20:37:11 iceman systemd[1]: Started v2-ui Service.
Nov 06 20:37:11 iceman systemd[10219]: v2-ui.service: Failed at step EXEC spawning /usr/local/v2-ui/v2-ui: Exec format error
Nov 06 20:37:11 iceman systemd[1]: v2-ui.service: Main process exited, code=exited, status=203/EXEC
Nov 06 20:37:11 iceman systemd[1]: v2-ui.service: Unit entered failed state.
Nov 06 20:37:11 iceman systemd[1]: v2-ui.service: Failed with result 'exit-code'.

日志如上.

**Comment by sprov065** [comment]
这个问题不太清楚，首先你要确定你的系统是64位的，CPU是amd64架构，如果是的话，请tg私聊我提供你的服务器进行测试。

**Comment by icemanstudy** [comment]
@sprov065
感谢回复.我的vps是256m内存,配置比较低,仅用来FQ,所以所以我安装debian和ubuntu时系统都选择的非64位的.是不是和这个有关系?下面是我尝试的几个系统.
debian-9.4-x86   失败
ubuntu-16.04-x86  失败
centos-7.5-x86_64   成功

**Comment by icemanstudy** [comment]
这是cpu信息
[root@iceman ~]# cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 13
model name      : QEMU Virtual CPU version 2.5+
stepping        : 3
microcode       : 0x1
cpu MHz         : 2799.998
cache size      : 16384 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pse3                                                                6 clflush mmx fxsr sse sse2 syscall nx lm rep_good nopl xtopology eagerfpu pni c                                                                x16 x2apic hypervisor lahf_lm
bogomips        : 5599.99
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual

**Comment by sprov065** [comment]
我已经明说了，只支持64位系统
