### ISSUE TITLE
Build from source

### ISSUE THREAD

**Issue by Tualua** [sprov065/v2-ui#128]
Hello! I would like to make some changes to source. For example, I use v2ray with ws and apache, so I don't need to add different port for each account, all account use the same 443 port,  just need to add new uuid. I think I found what I need to change, but there are no instructions how to build your project.

Could you help me with that?

Thanks

**Comment by Tualua** [comment]
Hello?

**Comment by sprov065** [comment]
Using python3.6, python library dependencies are written in the requirements.txt file.
