### ISSUE TITLE
[other]

### ISSUE THREAD

**Issue by MakeWater** [sprov065/v2-ui#129]
客户端系统：Mac OS X 10.14.6
服务端：Ubuntu 16.04

我使用v2ray-ui配置的账号在我Windows电脑上使用正常运行，但是创建配置第二个账号后复制配置链接 在Mac上的V2RayX（1.5.1版本，最新版）上面导入，或者手动输入相同配置都无法正常使用，请问是这个v2ray-ui 和Mac的客户端不兼容吗？有没有成功的案例？我只使用了纯tcp或者ws，没有加tls等伪装，IP没有被封。

**Comment by sprov065** [comment]
客户端的使用问题请自行研究
