### ISSUE TITLE
大佬,建议尝试加入caddy反代理和域名绑定,可以域名访问面板

### ISSUE THREAD

**Issue by lqhorochi** [sprov065/v2-ui#13]
大佬,建议尝试加入caddy反代理和域名绑定,可以域名访问面板

**Comment by LOVEChen** [comment]
附议

**Comment by sprov065** [comment]
自己安装caddy配置一下不就行了，这么懒吗，就算不用caddy也能用域名访问面板

**Comment by lyh458** [comment]
> 大佬,建议尝试加入caddy反代理和域名绑定,可以域名访问面板

众口难调吧。不是所有人都只是在vps上跑v2ray，还有一些基于ngnix、apache等搭了网站，端口占用、配置不统一等问题太多了。

**Comment by LOVEChen** [comment]
> 自己安装caddy配置一下不就行了，这么懒吗，就算不用caddy也能用域名访问面板

允许指定一个配置文件路径、重启参数和编辑窗口吧，老板，不是懒啊，是真的懒啊，就不用再开一个终端上去了，神作[手动点赞]
