### ISSUE TITLE
[多節點管理]是否能加入多節點的管理功能?

### ISSUE THREAD

**Issue by om0504** [sprov065/v2-ui#134]
**提问须知**
在此统一说明一下，面板只是一个方便你配置 v2ray 的工具，v2ray 没有的功能面板也没有办法去配置，比如有人问我 ss 能不能加个混淆、能不能限制设备数/网速等等，这些功能 v2ray 是没有的。
我不是 v2ray 作者，这些核心的功能你得去找 v2ray，只有 v2ray 有了面板才能进行配置，链接在此：https://github.com/v2ray/v2ray-core/issues。

**描述你想要的功能**
多個節點(server)在一個面板管理

**为何需要此功能**
可以一次查看不同節點的狀態

**其它说明**

**Comment by sprov065** [comment]
不会加入

**Comment by om0504** [comment]
瞭解，謝謝
