### ISSUE TITLE
[前端页面]可否在账号列表加一个分组功能

### ISSUE THREAD

**Issue by xmapst** [sprov065/v2-ui#135]
**提问须知**
在此统一说明一下，面板只是一个方便你配置 v2ray 的工具，v2ray 没有的功能面板也没有办法去配置，比如有人问我 ss 能不能加个混淆、能不能限制设备数/网速等等，这些功能 v2ray 是没有的。
我不是 v2ray 作者，这些核心的功能你得去找 v2ray，只有 v2ray 有了面板才能进行配置，链接在此：https://github.com/v2ray/v2ray-core/issues。

**描述你想要的功能**
可否在账号列表加一个分组功能

**为何需要此功能**
多用户且用户可能有多端口情况下，排序容易出现混乱

**其它说明**

**Comment by sprov065** [comment]
你们是要开多少用户啊

**Comment by xmapst** [comment]
假设有10个uuid，每个uuid有10-20个端口，虽然有备注，但是添加的时间不一样，排序就不一样，如果后期修改某个uuid或端口就得一个一个的去找。。。

**Comment by sprov065** [comment]
你这种拿一个小面板开几百个用户的也是无语了，你要商用麻烦买商用的，这种不适合你
