### ISSUE TITLE
单端口多用户（uuid）

### ISSUE THREAD

**Issue by Lhant** [sprov065/v2-ui#138]
请问您可否加入单端口多用户的功能，和几个人公用的一个服务器，使用ws+tls...如果有人员变动的话会很麻烦，可否加入此功能

**Comment by sprov065** [comment]
https://github.com/sprov065/v2-ui/issues?utf8=%E2%9C%93&q=is%3Aissue+%E5%8D%95%E7%AB%AF%E5%8F%A3+
