### ISSUE TITLE
[other]请问，ws+tls+cdn为什么不能翻墙？cloud flare返回521 错误，我试着关了cloudflare的代理发现可以翻了

### ISSUE THREAD

**Issue by Inferior-Gentleman** [sprov065/v2-ui#139]

**Comment by Inferior-Gentleman** [comment]
我的域名 returned a status 521. Try the options below to fix the issue.

1
Review the configuration between your origin server and Cloudflare and ensure that the origin resolves requests successfully

2
Review any existing Firewall Rules applied to your website which may be blocking access to 'Known Bots'

3
Contact Customer Support

**Comment by Inferior-Gentleman** [comment]
我换了个服务器，仍然显示521错误，但我关闭cdn代理后可以了 
但是我还想用反向代理这个功能，应该怎么办？

**Comment by sprov065** [comment]
这种问题要自己解决，更何况你没有描述清楚

**Comment by assmdx** [comment]
检查一下CloudFare TLS开关开了没有。
