### ISSUE TITLE
[feature]能否支持添加删除账号的时候不重启v2ray

### ISSUE THREAD

**Issue by miniaoe** [sprov065/v2-ui#140]
**提问须知**
在此统一说明一下，面板只是一个方便你配置 v2ray 的工具，v2ray 没有的功能面板也没有办法去配置，比如有人问我 ss 能不能加个混淆、能不能限制设备数/网速等等，这些功能 v2ray 是没有的。
我不是 v2ray 作者，这些核心的功能你得去找 v2ray，只有 v2ray 有了面板才能进行配置，链接在此：https://github.com/v2ray/v2ray-core/issues。

**描述你想要的功能**
在添加删除http协议账号时不重启v2ray

**为何需要此功能**
A已经连接了HTTP代理并正在下载东西，添加B账号的时候会重启v2ray，这个时候A会直接断无法再进行连接

**其它说明**

**Comment by sprov065** [comment]
请提供完整的不重启 v2ray 就能使账号生效的方案

**Comment by jy00566722** [comment]
更改任何配置，要生效都得重启吧。这是v2ray特性，与面板无关吧。
