### ISSUE TITLE
是否可以增加arm设备的支持

### ISSUE THREAD

**Issue by NoahNye** [sprov065/v2-ui#142]
有arm设备需要做透明代理，是否可以增加arm支持或者提供自己手动思路呢。

**Comment by sprov065** [comment]
安装python3，安装相应的依赖，就能直接运行源码了

**Comment by NoahNye** [comment]
谢谢，按您说的已经运行了。

**Comment by 393151606** [comment]
能否指导下需要什么依赖,根据报错提示安装不上

**Comment by yungjeff** [comment]
能否指导下? 我也是ARM，
请问如何安装使用？可否详细？

**Comment by yungjeff** [comment]
> 安装python3，安装相应的依赖，就能直接运行源码了

能否指导下? 我也是ARM，
请问如何安装使用？可否详细？
