### ISSUE TITLE
[feature]可选开启目的地覆盖、全局分组tls配置、单端口多用户

### ISSUE THREAD

**Issue by Chdkfd** [sprov065/v2-ui#146]
## 描述你想要的功能
* 可选开启目的地覆盖
* 全局分组tls配置
* 单端口多用户

## 为何需要此功能
* 作为前置代理时，Tor/I2P全挂
* 方便全局使用tls的服务器添加用户
* 便于多用户一次性配置反代

## 其它说明
* 无

**Comment by sprov065** [comment]
免费面板不要要求那么多

**Comment by SkyFuInMC** [comment]
那考虑一下可以开关“目的地覆盖”吧，Tor和I2P一个都用不了很不方便…
I2P想拿来备后患都不可能

**Comment by Chdkfd** [comment]
可以考虑一下添加配置“目的地覆盖”吗？

**Comment by sprov065** [comment]
请先给个 v2ray json 配置内容来解释一下什么是目的地覆盖

**Comment by Chdkfd** [comment]
> 请先给个 v2ray json 配置内容来解释一下什么是目的地覆盖

inboundSniffing
destinationOverride

**Comment by EdChdX** [comment]
可终于添加了，谢天谢地
