### ISSUE TITLE
ui调整

### ISSUE THREAD

**Issue by mottzz87** [sprov065/v2-ui#147]
**提问须知**
在此统一说明一下，面板只是一个方便你配置 v2ray 的工具，v2ray 没有的功能面板也没有办法去配置，比如有人问我 ss 能不能加个混淆、能不能限制设备数/网速等等，这些功能 v2ray 是没有的。
我不是 v2ray 作者，这些核心的功能你得去找 v2ray，只有 v2ray 有了面板才能进行配置，链接在此：https://github.com/v2ray/v2ray-core/issues。

**描述你想要的功能**
账号列表可以试用ant的table显示（只展示部分重要字段），具体的配置详情试用类似新建账号的弹窗来全量显示

**为何需要此功能**
管理页面table展示更加合理 单条数据的启/禁用、删除、重置功能操作更方便
目前账号列表的字段样式相对乱，操作不便 

**其它说明**

**Comment by sprov065** [comment]
本面板不推荐建立过多的用户
