### ISSUE TITLE
无法获取127.0.0.1上账号的流量

### ISSUE THREAD

**Issue by LOVEChen** [sprov065/v2-ui#15]
4.x开始无法正确获取在127.0.0.1上账号的流量 求修复 3.x的版本可以获取

**Comment by sprov065** [comment]
按理说是不会出现这个问题，自己检查看是不是哪里配置错误

**Comment by LOVEChen** [comment]
> 按理说是不会出现这个问题，自己检查看是不是哪里配置错误

老板 我是全部重新添加的账号 还是如此
泪流满面
我换个机器看看

**Comment by LOVEChen** [comment]
> 按理说是不会出现这个问题，自己检查看是不是哪里配置错误

4.1.0 重新安装一切正常了 感谢老板
