### ISSUE TITLE
加密方式可以不可以增加一个xchacha20的那个呢？

### ISSUE THREAD

**Issue by EricMzky** [sprov065/v2-ui#152]
**提问须知**
在此统一说明一下，面板只是一个方便你配置 v2ray 的工具，v2ray 没有的功能面板也没有办法去配置，比如有人问我 ss 能不能加个混淆、能不能限制设备数/网速等等，这些功能 v2ray 是没有的。
我不是 v2ray 作者，这些核心的功能你得去找 v2ray，只有 v2ray 有了面板才能进行配置，链接在此：https://github.com/v2ray/v2ray-core/issues 。

这个面板是我利用闲暇时间写的一个工具，并免费分享给大家用，经过了这么多版本迭代，面板的功能也更加的完善和稳定，现在已经可以满足绝大多数人的需求了，甚至多了很多功能，目前我也没有必要继续花费过多的精力和时间去免费满足极少数人的需求，之后我会减少在这个面板上投入的精力。如果你有更多个性化的定制需求，可以直接加入群组后找我定制。

**描述你想要的功能**

**为何需要此功能**

**其它说明**

**Comment by sprov065** [comment]
麻烦先去了解一下v2ray支持哪些加密

**Comment by EricMzky** [comment]
呃....我的意思是 在账号列表那里面有shadowsocks模式。加密有chacha等，但是shadowsocks也有xchacha加密方式。所以可以不可以多一个这个选项呢？选项

**Comment by sprov065** [comment]
我的意思是这个ss是直接用的v2ray内置的ss，v2ray内置的ss根本没有提供这个加密方式，加个选项有什么用呢
