### ISSUE TITLE
[other] 请问面板可以设置通过域名连接吗

### ISSUE THREAD

**Issue by GoodManWEN** [sprov065/v2-ui#156]
目前新服务器，系统ubuntu18.04 安装v2-ui后可以正常使用
想要请问一下比如服务器IP是20.20.20.20，另我有一个域名www.test.com已经解析到这个IP
通过v2ui可否设置连接地址为www.test.com而不是20.20.20.20

在网上看了一些说明似乎涉及到一些ui里不存在的配置选项？

**Comment by hamwang87** [comment]
我测试是可以的。
