### ISSUE TITLE
[other]修改证书路径后面板无法显示

### ISSUE THREAD

**Issue by yu4618** [sprov065/v2-ui#158]
1.centos7安装v2-ui一切正常，面板网页可以正常打开。

2.使用acme.sh生成证书。abcd.xyz是我真实域名的马赛克。
加密算法是ec-256，
提示：
Your cert is in  /root/.acme.sh/abcd.xyz_ecc/abcd.xyz.cer
Your cert key is in  /root/.acme.sh/abcd.xyz_ecc/abcd.xyz.key
The intermediate CA cert is in  /root/.acme.sh/abcd.xyz_ecc/ca.cer
And the full chain certs is there:  /root/.acme.sh/abcd.xyz_ecc/fullchain.cer

![1](https://user-images.githubusercontent.com/25944173/70777352-76a70000-1dba-11ea-8612-3ff1bbdd05fa.jpg)
随后我把
证书路径修改为：/root/.acme.sh/abcd.xyz_ecc/abcd.xyz.cer
秘钥路径修改为：/root/.acme.sh/abcd.xyz_ecc/abcd.xyz.key

3.此时，刷新面板网页，显示如下：
![2](https://user-images.githubusercontent.com/25944173/70777537-02b92780-1dbb-11ea-97ba-65d9a6e583cc.jpg)

Q1:除了重新安装以外，如何才能恢复面板正常显示？
Q2:若使用WS+TLS,证书和秘钥我这样配置有什么问题呢？

**Comment by yu4618** [comment]
面板通过/usr/local/v2-ui/v2-ui resetconfig重置了，但还是不知道该怎么正确配置证书路径。

**Comment by kzklot** [comment]
重新輸入網址並換上"**https://**xxx.com"
