### ISSUE TITLE
[feature]希望增加生成订阅源url更新节点的功能

### ISSUE THREAD

**Issue by dicrm** [sprov065/v2-ui#159]
**提问须知**
在此统一说明一下，面板只是一个方便你配置 v2ray 的工具，v2ray 没有的功能面板也没有办法去配置，比如有人问我 ss 能不能加个混淆、能不能限制设备数/网速等等，这些功能 v2ray 是没有的。
我不是 v2ray 作者，这些核心的功能你得去找 v2ray，只有 v2ray 有了面板才能进行配置，链接在此：https://github.com/v2ray/v2ray-core/issues 。

这个面板是我利用闲暇时间写的一个工具，并免费分享给大家用，经过了这么多版本迭代，面板的功能也更加的完善和稳定，现在已经可以满足绝大多数人的需求了，甚至多了很多功能，目前我也没有必要继续花费过多的精力和时间去免费满足极少数人的需求，之后我会减少在这个面板上投入的精力。如果你有更多个性化的定制需求，可以直接加入群组后找我定制。

**描述你想要的功能**
订阅，从URL更新 节点列表的功能。

**为何需要此功能**
比如我在后台设置了5个账号，5种不同的协议跟端口（因为担心节点被免费共享出去，所以这些端口协议偶尔需要改动）。如果有订阅源从url更新节点列表的功能，多个用户/朋友或者自己多台不同设备就可以通过这个订阅的模式实现自动更新节点信息。

**其它说明**

**Comment by huanauh** [comment]
附议

**Comment by zhangsean** [comment]
我也希望有这个功能！

**Comment by zhangsean** [comment]
怎么也不讨论就把这个关闭了呢？

**Comment by sprov065** [comment]
这个早就有人发过了，自己搜一下
