### ISSUE TITLE
通过iptables等防火墙设置端口限速

### ISSUE THREAD

**Issue by Blichus** [sprov065/v2-ui#165]
通过iptables等防火墙设置端口限速等操作，虽然官方没有支持。我觉得作者有这个能力通过防火墙实现一些规则。感谢。可以考虑一下。辛苦了！目前版本也很好。

**Comment by sprov065** [comment]
那有些系统没装iptables呢，有些系统用的是其它的替代品呢，有些人故意不想用iptables呢，有些人的iptables已经有一些自定义的规则了，万一把他的规则搞坏了咋整，不要以为就跑个命令就完事了，是很麻烦的，还容易出错。这类底层功能要等官方来实现，我只提供方便的配置功能。
