### ISSUE TITLE
[BUG]动态IP VPS使用v2-ui的问题

### ISSUE THREAD

**Issue by xytdyg** [sprov065/v2-ui#166]
添加用户的时候，需要设置监听IP。如果是动态IP的VPS，是不是就需要在VPS每次更换IP后重新修改监听IP呢？这个地方如果改成域名的话是否可以，因为我的域名设置了自动定时刷新IP的功能。
以上，感谢！

**Comment by sprov065** [comment]
监听IP没必要填实际IP，保持默认就行

**Comment by xytdyg** [comment]
好的，明白。我安装上试试，谢谢！
