### ISSUE TITLE
希望加入TCP+TLS 方式

### ISSUE THREAD

**Issue by lchsh** [sprov065/v2-ui#17]
**描述你想要的功能**
希望添加 TCP+TLS 方式

**为何需要此功能**
Shadowrocket 和 clash 等客户端均不支持 Http2 因此http+tls 无法使用
但TCP + TLS 大部分客户端均支持

**其它说明**

**Comment by sprov065** [comment]
已加入计划中，实际上小火箭扫http2二维码配置会有错误，因为它没有按vmess链接的格式来，而不是不能用http2
