### ISSUE TITLE
[feature]请问能否添加对shadowsocks-libev的支持？

### ISSUE THREAD

**Issue by YIZHEV** [sprov065/v2-ui#171]

**Comment by sprov065** [comment]
我也不造啊，你问问v2ray好不好

**Comment by sprov065** [comment]
这种问题就像是在问第三方telegram客户端能不能加上qq的功能

**Comment by YIZHEV** [comment]
sorry, 若有冒犯多有得罪。因为看到的ss功能，我还以为是和其他的类似于安装vmess和ss的脚本一样。所以才问出问题，不好意思不好意思，还要学习。
