### ISSUE TITLE
[feature]考虑在脚本中增加 [更新v2ray] 的功能。

### ISSUE THREAD

**Issue by 0x0004** [sprov065/v2-ui#173]
**描述你想要的功能**
在bash脚本中增加 [更新v2ray] 选项。

**为何需要此功能**
新版 v2ray会修复一些bug。

**Comment by sprov065** [comment]
可以

**Comment by zjn9011** [comment]
bash中选择“更新v2-ui”，就自动更新V2RayCore了 @0x0004

**Comment by Marukon** [comment]
建议将此功能加入到面板中，而不是bash中。

**Comment by sprov065** [comment]
> 建议将此功能加入到面板中，而不是bash中。

v2ray 目前更新并不频繁，并且也不一定有很大改动，想更新时自己登录 vps 更新一下就完事了
