### ISSUE TITLE
面板登录400

### ISSUE THREAD

**Issue by mqliutie** [sprov065/v2-ui#174]
通过ip或者域名都可以访问

[http://47.75.48.116:65432](http://47.75.48.116:65432)

使用 
用户名: admin
密码:  admin
点击登录,  400

**Comment by sprov065** [comment]
我这登录成功

**Comment by lloyd18** [comment]
我也登陆成功了

**Comment by mqliutie** [comment]
这么神奇么... 我一开始以为网络问题..  我手机热点也是400

**Comment by mqliutie** [comment]
可能是我chrome某些插件的原因?  我手机确实登录成功了

**Comment by mqliutie** [comment]
@sprov065 你代码有用到moment, lodash,axioas中的一个或几个么?  我为了方便, 我油猴全局注入了 `moment`, `_`, `axios`变量...  我怀疑污染了你的代码

**Comment by sprov065** [comment]
> @sprov065 你代码有用到moment, lodash,axioas中的一个或几个么? 我为了方便, 我油猴全局注入了 `moment`, `_`, `axios`变量... 我怀疑污染了你的代码

用了axios，这个你得自己解决一下
