### ISSUE TITLE
最新脚本在新增账户或者修改账户信息的时候容易导致服务报错

### ISSUE THREAD

**Issue by ericyyyy** [sprov065/v2-ui#176]
今天重新安装一键脚本以后.

因为在测试 WS+TLS 所有频繁的添加账户和修改账户配置.

然后就出现好多次 v2ray 状态: 错误  

因为看不到原因也不知道哪里报错 ,所以每次都要把账户信息全部删除,然后就正常了,请老大看看是不是添加账户的时候有什么BUG?

**Comment by ericyyyy** [comment]
刚才又测试了一遍,发现在修改备注的时候会导致服务器异常错误.麻烦老大测试一下?

**Comment by ericyyyy** [comment]
测试下来发现只要是修改配置就会报错,

**Comment by sprov065** [comment]
把配置信息发上来才能判断，包括面板的账号配置和config.json文件内容。自行隐藏敏感信息。

**Comment by sprov065** [comment]
已修复

**Comment by ericyyyy** [comment]
感谢您的修复也就是说我 直接 在V2-UI 脚本里面选择2 更新即可吗？
