### ISSUE TITLE
[feature]什么时候能够支持mysql数据库

### ISSUE THREAD

**Issue by leo985** [sprov065/v2-ui#182]
什么时候能支持mysql数据库？

多个机器db数据可以用一份。不需要做数据同步。

**Comment by flyingOrange** [comment]
对，这个很关键，可以用一个管理系统管理多个服务器。
希望可以设置到期时间，然后到期后自动停止。

**Comment by leo985** [comment]
调整了一下，目前已经支持mysql了，想利用原有的打包安装脚本，可否把打包成linux可执行文件的脚本也放到仓库里面？

**Comment by Angel0726** [comment]
> 调整了一下，目前已经支持mysql了，想利用原有的打包安装脚本，可否把打包成linux可执行文件的脚本也放到仓库里面？

请问一下如何使用mysql管理多台服务器，可以出一个教程吗？
