### ISSUE TITLE
[other]在自己vps上装好不做任何修改后在自己windows电脑上的v2rayn如何配置呢

### ISSUE THREAD

**Issue by Aesuib** [sprov065/v2-ui#183]
在自己vps上装好不做任何修改后在自己windows电脑上的v2rayn如何配置呢？我看v2ui初始默认的v2ray的配置文件里面inbound没有配成vmess，也没有用户id，那我的客户端v2uin里面的配置怎么做呢？

**Comment by sprov065** [comment]
需要进入面板自己添加一个账号
