### ISSUE TITLE
[other]账号与密码修改

### ISSUE THREAD

**Issue by Takdrift** [sprov065/v2-ui#184]
sprov065：

你好，关于面板账户密码的修改说明以及选项我找了一圈issues，翻了你的blog并且google之后都没找到答案。

请问如何修改账户与密码，谢谢！

祝新年快乐！

Takdrift

**Comment by sprov065** [comment]
面板设置里

**Comment by Takdrift** [comment]
![image](https://user-images.githubusercontent.com/32677715/73828314-fa6ded80-483b-11ea-81c9-f13d1bc0347f.png)
抱歉，看的太不仔细了，哈哈。

谢谢！
