### ISSUE TITLE
[BUG]使用nginx反代后页面可显示标题“login”，但页面一片空白

### ISSUE THREAD

**Issue by lixiang810** [sprov065/v2-ui#191]
# 提问须知
 - 先仔细阅读博客文章及评论，查看是否有相关问题和解决方案，再查看所有 issues，包括已开启的和已关闭的，确认没有任何地方可以解决你的问题时再提问。
 - 如果是 v2ray 本身的问题，请找 v2ray 官方，而不是在这里问。
 - 如果是你自身的技术知识积累不够，例如 xxx 不会配置，xx 软件不会用，配置错误导致连不上等等问题。你可以换一个提问模板进行提问，而不是 BUG 反馈模板。此类问题我一般不会做回答，除非是有意义的问题。建议多学习相关技术，积累自身的技术水平。
 - 如果需要上传图片，直接将图片拖入此文本框即可。
 - 提问的艺术：https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md

**描述你的问题**
请尽可能的精确描述你的问题，尽量不要使用笼统的词汇。
使用nginx反代后页面可显示标题“login”，但页面一片空白，f12可看到一些元素。与此同时，使用ip访问页面（加path）依然正常（未设置仅监听127.0.0.1）。
nginx.conf相关部分：

> location /vtui
>     {
>       proxy_redirect off;
>       proxy_pass http://127.0.0.1:65432/vtui;
>       proxy_http_version 1.1;
>       proxy_set_header Upgrade $http_upgrade;
>       proxy_set_header Connection "upgrade";
>       proxy_set_header Host $host;
>       proxy_set_header X-Real-IP $remote_addr;
>       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>     }

面板“网页根路径”项设为“/vtui”，其它为默认。
![批注 2020-02-11 191016](https://user-images.githubusercontent.com/14120445/74231861-87b0b680-4d02-11ea-8612-02ee270cf812.png)
上图为ip正常访问
![批注 2020-02-11 1910162](https://user-images.githubusercontent.com/14120445/74231864-8b443d80-4d02-11ea-873b-d221fb27943a.png)
上图为域名访问异常

**面板是否正常运行**
>提示：systemctl status v2-ui -l
正常

**与问题相关的面板日志及其他内容**
>提示：cat /etc/v2-ui/v2-ui.log
无

**你所使用的面板版本**
最新（5.1.2）

**你所使用的系统（服务器）**
centos 7，VPS提供商为hostwinds

**你所使用的浏览器**
firefox+chrome

**你猜测可能的原因**
我的服务器ip被墙，所有操作均用代理完成。域名有cloudflare的CDN，不知是否与问题有关。
(已排除cloudflare CDN问题，关闭CDN后，用代理访问我的域名，问题依旧）

**Comment by lixiang810** [comment]
![批注 2020-02-11 191658](https://user-images.githubusercontent.com/14120445/74232119-18879200-4d03-11ea-975b-e0f865b38702.png)
图为浏览器f12输出

**Comment by sprov065** [comment]
https://github.com/sprov065/v2-ui/issues/24
参考这个issue

**Comment by lixiang810** [comment]
> 
> 
> #24
> 参考这个issue

解决了！非常感谢。
原因在于宝塔面板建站默认把js给伪静态了。
这个问题与你的项目完全无关，是我自己的配置问题。同时我也没有给出与排查这个问题有关的nginx.conf的部分。因此感谢你的无偿帮助。
