### ISSUE TITLE
在自行修改账号的uuid之后有概率出现v2ray错误导致无法使用

### ISSUE THREAD

**Issue by Hanyokign** [sprov065/v2-ui#192]
uuid的尾数是7，我改成了8，保存之后一会儿后出现v2ray运行状态为错误，我删除那个账号之后，v2ray恢复正常。偶尔出现，并不是每次更改都会出现该错误。改了十几次出现了2次

**Comment by sprov065** [comment]
请使用专门的uuid生成器
