### ISSUE TITLE
新增的tcp + tls方式缺少 tcpSettings字段

### ISSUE THREAD

**Issue by lchsh** [sprov065/v2-ui#20]
**Describe the bug**
新建 tcp + tls 配置时 发包内容缺少字段
port: 27918
listen: 0.0.0.0
protocol: vmess
settings: {"clients":[{"id":"2eed0a6a-86ec-4d58-9f9e-3ee48b08378c","alterId":64}]}
stream_settings: {"network":"tcp","security":"tls","tcpSettings":{"type":"none"}}
remark: test1

bug分析 js未修改 tcp
v2_classes.js line 494

 tlsSettings: security === 'tls' && ['ws', 'http', 'quic'].indexOf(network) >= 0 ? this.tls.toJson() :

**Comment by sprov065** [comment]
下个版本修复
