### ISSUE TITLE
考虑到nat机子会强制固定端口，可否在脚本上自定义访问端口

### ISSUE THREAD

**Issue by wnxkiwi** [sprov065/v2-ui#202]
**描述你想要的功能**
您好：作者
      首先感谢您写的这个功能，很好用，非常感谢。
      我想要的功能：考虑到有些厂商的nat机子会强制固定端口，我可否请求：在脚本安装时候，增加一个功能------能让我们输入想要的访问端口，而非65432。

**为何需要此功能**
      因为厂商的65432不开放，就无法访问到页面，无法访问到页面也就无法修改访问端口，变成一个无法解开的循环了。

**其它说明**
     衷心希望能添加此功能，麻烦了。

**Comment by sprov065** [comment]
输入 v2-ui 命令，你会看到你想要的
