### ISSUE TITLE
[other]如何进行手动安装呢

### ISSUE THREAD

**Issue by Himalaya2020** [sprov065/v2-ui#217]
国内服务器真的是煎熬呀，如何进行手动安装呢？

**Comment by sprov065** [comment]
有空了补个教程

**Comment by myfingerhurt** [comment]
@Himalaya2020 

Look what is inside this script and do everything manually. 
https://blog.sprov.xyz/v2-ui.sh

**Comment by sprov065** [comment]
已更新手动安装教程

**Comment by Himalaya2020** [comment]
> 已更新手动安装教程

谢谢！
