### ISSUE TITLE
流量统计定时任务会卡住。

### ISSUE THREAD

**Issue by leo985** [sprov065/v2-ui#229]
现象：数据库的流量统计字段不再更新。
进一步跟踪：
使用v2ray自身的流量统计命令查看流量，正常。但是v2-ui并没有将v2ray的统计的流量汇总到数据库中。如果重启v2-ui后则恢复正常。

**Comment by sprov065** [comment]
这个在极小的几率下会出现，主要原因是因为v2ctl的命令会卡住

**Comment by leo985** [comment]
概率好像不是非常小，半个月已经遇到2次了。能否优化下。设置超时，卡住的话就抛出异常。重新发起轮询。

**Comment by sprov065** [comment]
应该已修复
