### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Potterli20** [sprov065/v2-ui#23]
**描述你的问题**

放行端口:[65432] | 未使用 | 2019-08-12 10:42:32 | q
-- | -- | -- | --

**与问题相关的面板日志及其他内容**

**你所使用的面板版本**
v4.1.1

**你所使用的系统（服务器）**
ubuntu18.04.3

**你所使用的浏览器**
firefox nightly

**你猜测可能的原因**
宝塔面板

**Comment by sprov065** [comment]
问题描述不清，如果是面板启动失败，则提供相关日志及其它更详细的资料。

端口占用等问题自行解决，宝塔问题自行解决。

**Comment by Potterli20** [comment]
> 问题描述不清，如果是面板启动失败，则提供相关日志及其它更详细的资料。
> 
> 端口占用等问题自行解决，宝塔问题自行解决。

端口已经开放，而且没有错误log，你叫我如何自行解决

**Comment by sprov065** [comment]
```
systemctl statuc v2-ui -l

cat /etc/v2-ui/v2-ui.log
```

**Comment by Potterli20** [comment]
> systemctl status v2-ui -l
root@potter:/etc# systemctl status v2-ui -l
● v2-ui.service - v2-ui Service
   Loaded: loaded (/etc/systemd/system/v2-ui.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2019-08-12 10:43:52 CST; 6h ago
  Process: 27733 ExecStart=/usr/local/v2-ui/v2-ui (code=exited, status=255)
 Main PID: 27733 (code=exited, status=255)


root@potter:/etc# cat /etc/v2-ui/v2-ui.log
cat: /etc/v2-ui/v2-ui.log: No such file or directory
