### ISSUE TITLE
ws+tls 证书路径问题 

### ISSUE THREAD

**Issue by ramocky** [sprov065/v2-ui#232]
这个证书是不是对格式有要求 crt 还是 pem  配置路径是绝对路径吗我把证书目录塞进去类似于/etc/ssl/caddy/acme/acme-v02.api.letsencrypt.org/sites/domain.xxxx/
然后 v2ray 报错了

**Comment by sprov065** [comment]
你填的大概是目录吧

**Comment by beckball** [comment]
同作者所说 填写的是目录
请具体填写文件路径/文件名
