### ISSUE TITLE
[BUG]客户端导入面板生成的链接，导入客户端时，allowInsecure参数为false，导致无法正常使用

### ISSUE THREAD

**Issue by SKEETCHAN** [sprov065/v2-ui#238]
**描述你的问题**
面板配置账户时，开启允许不安全之后 面板生成的链接，导入到Windows客户端V2rayN （V3.14 2020/04/08）时，配置选项allowInsecure为 False，导致无法正常访问。需要手动，将客户端的处allowInsecure参数为True。

**面板相关配置信息**
>提供与问题相关的面板账号信息截图，面板设置截图，v2ray config.json 内容等，自行打码敏感信息
![批注 2020-04-09 010105](https://user-images.githubusercontent.com/40740405/78812816-95cb3c80-79fe-11ea-865b-21046d29a2a6.png)
![批注 2020-04-09 010603](https://user-images.githubusercontent.com/40740405/78812821-97950000-79fe-11ea-820c-d7304479ab94.png)

**Comment by sprov065** [comment]
这是客户端自己的行为，与服务端没有关系，标准的vmess链接不包含allowInsecure这一项

**Comment by beckball** [comment]
vmess链接无法包含这个参数
而且allowInsecure为True时才符合你面板上呈现的结果

**Comment by SKEETCHAN** [comment]
原来是这样，因为我之前用低版本的客户端2.64（应该是），面板导入的时候这个数值默认是缺省的。所以也能正常连接，结果昨天覆盖升级下客户端后，发现无法链接了，排除了下发现时配置的问题，导入链接后，那个位置从默认缺省变成了false所以没法连接，以为是面板的问题。

**Comment by SKEETCHAN** [comment]
> 这是客户端自己的行为，与服务端没有关系，标准的vmess链接不包含allowInsecure这一项
原来是这样，因为我之前用低版本的客户端2.64（应该是），面板导入的时候这个数值默认是缺省的。所以也能正常连接，结果昨天覆盖升级下客户端后，发现无法链接了，排除了下发现时配置的问题，导入链接后，那个位置从默认缺省变成了false所以没法连接，以为是面板的问题。

**Comment by beckball** [comment]
> 这是客户端自己的行为，与服务端没有关系，标准的vmess链接不包含allowInsecure这一项

v2rayN 3.14版本生成的链接已经可以附带tls以及其allowInsecure参数 修复于[3.13](https://github.com/2dust/v2rayN/pull/612)
v2rayNG也已经在[1.25](https://github.com/2dust/v2rayNG/releases/tag/1.2.5)增加了此选项
希望面板能够跟进 谢谢

**Comment by sprov065** [comment]
> > 这是客户端自己的行为，与服务端没有关系，标准的vmess链接不包含allowInsecure这一项
> 
> v2rayN 3.14版本生成的链接已经可以附带tls以及其allowInsecure参数 修复于[3.13](https://github.com/2dust/v2rayN/pull/612)
> v2rayNG也已经在[1.25](https://github.com/2dust/v2rayNG/releases/tag/1.2.5)增加了此选项
> 希望面板能够跟进 谢谢

你发的这两个跟vmess链接格式没有关系，只不过是客户端功能改进而已
