### ISSUE TITLE
[other]请问面板是不是支持管理很多台vps 

### ISSUE THREAD

**Issue by bannedbook** [sprov065/v2-ui#239]
1、请问面板是不是支持管理很多台vps ,就是面板单独一台机，然后其它很多 v2ray节点分布在很多 台vps上？
2、面板可否监控这些v2ray节点是否在线
3、面板可否监控这些v2ray节点是否被墙

**Comment by beckball** [comment]
1这是一个单vps 使用GUI操作服务端配置的面板
2可以使用Nodequery 或者 其他探针程序
3请使用其他脚本或者网站检测
