### ISSUE TITLE
nginx反向代理面板网页端报404

### ISSUE THREAD

**Issue by ZeenYe** [sprov065/v2-ui#24]
想通过Nginx反代面板实现https访问，nginx添加了location规则，面板上配置了自定义路径，访问时可以访问到html页面，但css和js都访问不到，如何解决？

**Comment by sprov065** [comment]
先看博客文章，严格按照文章的说明配置https。nginx其它自定义的配置若与面板有冲突，请自行解决。

**Comment by ZeenYe** [comment]
已核对过博客文章，配置一致。Nginx添加的匹配规则如下：
![image](https://user-images.githubusercontent.com/19652272/62848729-664d1e80-bd0f-11e9-98d3-4c841d3ae7e6.png)
面板配置如下：设置的路径是/panel
![image](https://user-images.githubusercontent.com/19652272/62848751-79f88500-bd0f-11e9-89ac-cd2dcf87a96b.png)
使用ip地址和端口加路径可以访问到面板，但是用域名加路径访问就不行。
使用ip地址和端口加路径访问如下：
![image](https://user-images.githubusercontent.com/19652272/62849110-f0e24d80-bd10-11e9-8fc6-10a7180c5a88.png)

使用域名加路径访问如下：
访问/panel/的时候是正常的，拿到了html的内容
![image](https://user-images.githubusercontent.com/19652272/62849334-d8266780-bd11-11e9-838f-5bd875723d45.png)
解析html去拿css和js文件的时候就不行了，以/panel/static开头的url都是返回404
![image](https://user-images.githubusercontent.com/19652272/62849131-08b9d180-bd11-11e9-8bcc-3fdc2d85ecf5.png)

**Comment by sprov065** [comment]
查看 nginx 其它配置，很有可能是因为你单独配置了静态文件的访问，导致访问面板的静态文件时 nginx 没有访问面板，而是从其它地方找了。

**Comment by ZeenYe** [comment]
多谢指导！根据你提供的思路，查到原因是 nginx 配置的防盗链正则匹配优先级高于 /panel 普通匹配，将"location /panel {}"改为"location ^~ /panel"，阻止匹配正则后可成功用https访问面板

**Comment by swatchmax** [comment]
@ggimonmyway, I've just repeat your nginx config. Sign in page opens. But after login/password it throws that error 网络错误，请检查网络连接. Login/pass are 100% correct. What maybe wrong?
