### ISSUE TITLE
[other]ip被墙了还能打开面板么

### ISSUE THREAD

**Issue by AKMaS** [sprov065/v2-ui#240]
# 提问须知
 - 先仔细阅读博客文章及评论，查看是否有相关问题和解决方案，再查看所有 issues，包括已开启的和已关闭的，确认没有任何地方可以解决你的问题时再提问。
 - 如果是 v2ray 本身的问题，请找 v2ray 官方，而不是在这里问。
 - 如果是你自身的技术知识积累不够，例如 xxx 不会配置，xx 软件不会用，配置错误导致连不上等等问题。你可以换一个提问模板进行提问，而不是 BUG 反馈模板。此类问题我一般不会做回答，除非是有意义的问题。建议多学习相关技术，积累自身的技术水平。
 - 如果需要上传图片，直接将图片拖入此文本框即可。
 - 提问的艺术：https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md

**描述你的问题**
>请尽可能的精确描述你的问题，尽量不要使用笼统的词汇。
  我的ip之前被墙了，现在按照面板配置好了，但是不同通过ip打开面板

**面板相关配置信息**
>提供与问题相关的面板账号信息截图，面板设置截图，v2ray config.json 内容等，自行打码敏感信息
**面板是否正常运行**
>提示：systemctl status v2-ui -l
 面板正常运行
   Apr 09 08:42:06 172.96.200.11.16clouds.com systemd[1]: Started v2-ui Service.
   Apr 09 08:42:06 172.96.200.11.16clouds.com systemd[1]: Starting v2-ui Service...
端口打开
firewall-cmd --zone=public --list-ports 
 65432/tcp
**与问题相关的面板日志及其他内容**
>提示：cat /etc/v2-ui/v2-ui.log
 无

**你所使用的面板版本**
最新

**你所使用的系统（服务器）**
Centos 7 x86_64 bbr

**你所使用的浏览器**
chrome/safari

**你猜测可能的原因**
ip墙了，国内访问不了？

**Comment by beckball** [comment]
是的

**Comment by WangWenBin2017** [comment]
曲线救国，套cloudflare修改管理端口为cf支持的其他端口，比如 https://support.cloudflare.com/hc/zh-cn/articles/200169156-%E8%AF%86%E5%88%AB%E4%B8%8E-Cloudflare-%E7%9A%84%E4%BB%A3%E7%90%86%E5%85%BC%E5%AE%B9%E7%9A%84%E7%BD%91%E7%BB%9C%E7%AB%AF%E5%8F%A3
，然后访问，亲测有效。

**Comment by sprov065** [comment]
这是显而易见的问题。。
