### ISSUE TITLE
[BUG]加密协议错误

### ISSUE THREAD

**Issue by qzydustin** [sprov065/v2-ui#243]
shadowsocks中加密
method： chacha20-poly1305
其实应该是chacha20-ietf-poly1305

shadowrocket中选择chacha20-poly1305连不上
选择chacha20-ietf-poly1305可以连上

google说这两种协议是同一种，但是应该是有些差别的
如果可以改一下生成图片和链接就更好了
感谢

**Comment by sprov065** [comment]
这是v2ray的加密选项配置，我不能乱改名称
