### ISSUE TITLE
[other]windows电脑都不能用v2ray连接

### ISSUE THREAD

**Issue by bumblebee309** [sprov065/v2-ui#247]
安卓ios和macos都莫得问题，但是只有v2rayN连不上，没启用http+tls，ssr协议也连不上。手里的windows和朋友的windows都不行。

**Comment by sprov065** [comment]
要么自己配置有误，使用方式不当，要么是客户端bug等等，跟我这边没关系

PS：问问题好歹上一些截图一些关键信息给人家看，光说连不上谁知道什么原因
