### ISSUE TITLE
[feature]希望面板内添加"sniffing"选项的开关功能。

### ISSUE THREAD

**Issue by chaosye0** [sprov065/v2-ui#248]
**描述你想要的功能**
如题，希望面板内添加"sniffing"选项的开关功能。

**为何需要此功能**
有关sniffing的语句在配置文件中如下
  ```
    "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
```
分别在客户端和服务端配置文件中都有，这个选项是v2rayng里的“开启流量探测”功能，有关这个功能的介绍[官方文档里](https://toutyrater.github.io/basic/vmess.html)是：

> 在客户端配置的 inbounds 中，有一个 "sniffing" 字段，V2Ray 手册解释为“流量探测，根据指定的流量类型，重置所请求的目标”，这话不太好理解，简单说这东西就是从网络流量中识别出域名。这个 sniffing 有两个用处：
> 
> 解决 DNS 污染；
> 对于 IP 流量可以应用后文提到的域名路由规则；
> 识别 BT 协议，根据自己的需要拦截或者直连 BT 流量(后文有一节专门提及)

由于这个功能和tor浏览器冲突，而且必须服务端和客户端都关闭的情况下才能连上tor浏览器。
我试着更改服务器上的/etc/v2ray/config.json, 但是重启面板后就这个文件就自动恢复了。所以希望面板里增加这个功能的开关选项。万分感谢。

**其它说明**
说一下用到tor浏览器的原因吧，跟暗网也没什么关系，纯粹是因为这玩意是匿名的，能挂代理下SCI-HUB上的文献。。。正常挂代理sci-hub这网站会直接就报错。。

**Comment by chaosye0** [comment]
我已经拿其它脚本试过了，在服务端和客户端都写成 "sniffing": { "enabled": false,就能不使用网桥直接连上tor（使用网桥tor的速度会特别慢） 
```
 "sniffing": {
      "enabled": false,
```

**Comment by sprov065** [comment]
最新版已加入
