### ISSUE TITLE
[BUG]重启面板后配置文件重置

### ISSUE THREAD

**Issue by beckball** [sprov065/v2-ui#25]
**描述你的问题**
运行重启面板命令后 v2配置文件重置为预设模板样式 不知这算不算一个bug
同时希望能够像上一代面板自动读取配置文件并填写账号设置 但是上一代对动态端口的支持不太好 望采纳！

**面板是否正常运行**
运行正常

**与问题相关的面板日志及其他内容**
无报错

**你所使用的面板版本**
4.1.1

**你所使用的系统（服务器）**
Debian 9

**你所使用的浏览器**
Chrome 76

**你猜测可能的原因**
设计原因

**Comment by sprov065** [comment]
非bug，就是这么设计的，如果需要修改v2ray配置文件，到面板设置里修改v2ray配置文件模板
