### ISSUE TITLE
[BUG]面板500错误

### ISSUE THREAD

**Issue by cxy5014** [sprov065/v2-ui#252]
# 提问须知
 - 先仔细阅读博客文章及评论，查看是否有相关问题和解决方案，再查看所有 issues，包括已开启的和已关闭的，确认没有任何地方可以解决你的问题时再提问。
 - 如果是 v2ray 本身的问题，请找 v2ray 官方，而不是在这里问。
 - 如果是你自身的技术知识积累不够，例如 xxx 不会配置，xx 软件不会用，配置错误导致连不上等等问题。你可以换一个提问模板进行提问，而不是 BUG 反馈模板。此类问题我一般不会做回答，除非是有意义的问题。建议多学习相关技术，积累自身的技术水平。
 - 如果需要上传图片，直接将图片拖入此文本框即可。
 - 提问的艺术：https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md

**描述你的问题**
>请尽可能的精确描述你的问题，尽量不要使用笼统的词汇。

面板500错误
**面板相关配置信息**
>提供与问题相关的面板账号信息截图，面板设置截图，v2ray config.json 内容等，自行打码敏感信息

**面板是否正常运行**
>提示：systemctl status v2-ui -l
 Loaded: loaded (/etc/systemd/system/v2-ui.service; enabled; vendor preset: en
   Active: active (running) since Sun 2020-04-26 09:12:39 EDT; 7min ago

**与问题相关的面板日志及其他内容**
>提示：cat /etc/v2-ui/v2-ui.log
Traceback (most recent call last):
  File "tornado/web.py", line 1676, in _execute
  File "tornado/web.py", line 3022, in prepare
  File "tornado/wsgi.py", line 114, in __call__
  File "flask/app.py", line 2463, in __call__
  File "flask/app.py", line 2449, in wsgi_app
  File "flask/app.py", line 1878, in handle_exception
  File "init.py", line 101, in error_handle
AttributeError: 'InternalServerError' object has no attribute 'msg'
2020-04-26 09:13:10-tornado.access-ERROR-500 GET / (127.0.0.1) 12.77ms
**你所使用的面板版本**
5.2.0

**你所使用的系统（服务器）**
Ubuntu 18.03

**你所使用的浏览器**

**你猜测可能的原因**

**Comment by cxy5014** [comment]
root@*:~# curl 127.0.0.1:65432
<html><title>500: Internal Server Error</title><body>500: Internal Server Error</body></html>

**Comment by sprov065** [comment]
先备份db文件，尝试卸载重装，看能否复现此问题

**Comment by cndanili** [comment]
我也发现这个问题了，如果浏览器使用中文为第一语言就没有这个问题，如果是英文就会出现这个情况，而且就今天更新了才出现，老版本没问题。

**Comment by sprov065** [comment]
> 我也发现这个问题了，如果浏览器使用中文为第一语言就没有这个问题，如果是英文就会出现这个情况，而且就今天更新了才出现，老版本没问题。

使用的什么浏览器，什么版本

**Comment by cndanili** [comment]
> > 我也发现这个问题了，如果浏览器使用中文为第一语言就没有这个问题，如果是英文就会出现这个情况，而且就今天更新了才出现，老版本没问题。
> 
> 使用的什么浏览器，什么版本

在Mac OS下使用Safari时会出现这样的错误，在Mac OS下使用Google Chrome正常使用，显示中文界面。在iOS使用Safari和Chrome都出现Internal Server Error 500的错误。Mac OS和 iOS使用的是英文系统。老版本的Safari打开显示的是英文界面。

**Comment by sprov065** [comment]
> > > 我也发现这个问题了，如果浏览器使用中文为第一语言就没有这个问题，如果是英文就会出现这个情况，而且就今天更新了才出现，老版本没问题。
> > 
> > 
> > 使用的什么浏览器，什么版本
> 
> 在Mac OS下使用Safari时会出现这样的错误，在Mac OS下使用Google Chrome正常使用，显示中文界面。在iOS使用Safari和Chrome都出现Internal Server Error 500的错误。Mac OS和 iOS使用的是英文系统。老版本的Safari打开显示的是英文界面。
> 
> 现在用的是5.2.0版本，之前使用的是5.1.2版本

更新了，试一下

**Comment by cndanili** [comment]
> > > > 我也发现这个问题了，如果浏览器使用中文为第一语言就没有这个问题，如果是英文就会出现这个情况，而且就今天更新了才出现，老版本没问题。
> > > 
> > > 
> > > 使用的什么浏览器，什么版本
> > 
> > 
> > 在Mac OS下使用Safari时会出现这样的错误，在Mac OS下使用Google Chrome正常使用，显示中文界面。在iOS使用Safari和Chrome都出现Internal Server Error 500的错误。Mac OS和 iOS使用的是英文系统。老版本的Safari打开显示的是英文界面。
> > 现在用的是5.2.0版本，之前使用的是5.1.2版本
> 
> 更新了，试一下

正常了！
之前还以为是浏览器缓存的问题，一不小心把Safari的浏览记录都给删除了，心疼。

**Comment by cxy5014** [comment]
可以正常使用了，谢谢！
