### ISSUE TITLE
[BUG]生成的二维码通过软件导入后丢失其中的选项

### ISSUE THREAD

**Issue by xuexiaokang** [sprov065/v2-ui#254]
**描述你的问题**
生成的二维码通过软件导入后丢失其中的选项【允许不安全：】，导致都要在软件中手工去设置允许不安全是否开启

**面板相关配置信息**

**面板是否正常运行**
正常运行

**与问题相关的面板日志及其他内容**

**你所使用的面板版本**
5.1.2

**你所使用的系统（服务器）**
Debian

**你所使用的浏览器**
chrome

**你猜测可能的原因**
配置文件里缺少了“允许不安全”这个项目应用情况的导出

**Comment by sprov065** [comment]
重复问题，https://github.com/sprov065/v2-ui/issues/238
