### ISSUE TITLE
gfw批量扫65432可能成为特征

### ISSUE THREAD

**Issue by ntgeralt** [sprov065/v2-ui#260]

**Comment by sprov065** [comment]
如果觉得不妥，自己换个端口就完事了。

我觉得在65432开放了一个http服务不可能能作为一个fq特征，这端口又不是v2-ui独有，并且这端口很容易被人用到。

与其检测这玩意，gfw还不如多搞搞流量分析来得实在些

**Comment by ntgeralt** [comment]
按照国家算力批量扫海外ip某一个端口用不了几秒，放在常见端口让它不敢扫还好
