### ISSUE TITLE
[feature] 可以加一个单用户流量使用额度限制吗

### ISSUE THREAD

**Issue by chaseSpace** [sprov065/v2-ui#262]
**描述你想要的功能**
设置一个账户的流量使用限制，如一个用户id只能使用1G，流量用尽无法继续使用（而不是手动禁用）

**Comment by fanmli** [comment]
我也希望作者能添加这个功能，再次感谢作者！

**Comment by VeryAdd** [comment]
作者的新产品就有这个功能了，可以去学习看看

**Comment by chaseSpace** [comment]
@VeryAdd 在哪儿呢

**Comment by nkxingxh** [comment]
我也希望这样，但是我找不到

> 作者的新产品就有这个功能了，可以去学习看看

**Comment by loongwind** [comment]
> 作者的新产品就有这个功能了，可以去学习看看

我也没找到
