### ISSUE TITLE
[other]nginx反代登录页面可显示标题，但页面一片空白

### ISSUE THREAD

**Issue by Datadelete10426** [sprov065/v2-ui#266]
已经参照 #24 #191 #200 删除了如下段落：

    location ~ \.well-known{
        allow all;
    }
    
    location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$
    {
        expires      30d;
        error_log off;
        access_log off;
    }
    
    location ~ .*\.(js|css)?$
    {
        expires      12h;
        error_log off;
        access_log off; 
    }
或者在反代段落中阻止匹配正则

          location ^~ /user {
             proxy_pass http://127.0.0.1:65432/;
             proxy_set_header Host $host;
             proxy_set_header X-Real-IP $remote_addr;
             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          }
但无论使用那种办法，加载出来的页面都仍是空白
![批注 2020-05-25 005800](https://user-images.githubusercontent.com/60697024/82760005-685a1700-9e23-11ea-96b2-83ae777ca64f.png)

与用IP访问，正常加载的界面相比较，有那么一行有明显区别
![批注 2020-05-25 005738](https://user-images.githubusercontent.com/60697024/82760035-8de72080-9e23-11ea-870c-b9661f69a9fd.png)

不知道是我的操作有问题，还是需要什么别的方法……

**Comment by sprov065** [comment]
反代 location /xxx
面板网页根路径也要设置为/xxx

**Comment by Datadelete10426** [comment]
> 反代 location /xxx
> 面板网页根路径也要设置为/xxx

好了🤔👌
