### ISSUE TITLE
[other]油管访问问题

### ISSUE THREAD

**Issue by Simon-chy** [sprov065/v2-ui#269]
用了一键脚本部署，用起来很方便，十分感谢！
但是发现一个问题，油管的视频可以看，但是评论区一直在转圈就是读不出来，试过PAC和全局模式。

其他网站的评论区貌似是OK的，试了比如NYT

有可能是哪方面问题呢？希望给指指路我去尝试，谢谢！

**Comment by alanleung2017** [comment]
> 用了一键脚本部署，用起来很方便，十分感谢！
> 但是发现一个问题，油管的视频可以看，但是评论区一直在转圈就是读不出来，试过PAC和全局模式。
> 
> 其他网站的评论区貌似是OK的，试了比如NYT
> 
> 有可能是哪方面问题呢？希望给指指路我去尝试，谢谢！

你主机或者本地网络的问题吧，我新加坡的节点，评论正常啊
