### ISSUE TITLE
[feature]建议加入官方认可的协议组合

### ISSUE THREAD

**Issue by jiemo9527** [sprov065/v2-ui#273]
建议加入官方认可的协议组合，一些不基于tls的协议存在风险。

![image](https://user-images.githubusercontent.com/36528975/83739276-f6d26200-a687-11ea-8649-0285dbd7194d.png)
公告传送门：https://github.com/v2ray/v2ray-core/issues/2542

**Comment by sprov065** [comment]
都支持啊，除了shadowsocks over websocket那个以外，因为没有客户端能支持

**Comment by jiemo9527** [comment]
弱弱问一句，vmess over tls如何设置，面板上好像必须要选个传输协议

**Comment by cadixu** [comment]
> 弱弱问一句，vmess over tls如何设置，面板上好像必须要选个传输协议

vmess over tls就是協議vmess + 開啟tls

**Comment by jiemo9527** [comment]
> > 弱弱问一句，vmess over tls如何设置，面板上好像必须要选个传输协议
> 
> vmess over tls就是協議vmess + 開啟tls

你这等于没说

**Comment by cadixu** [comment]
> > > 弱弱问一句，vmess over tls如何设置，面板上好像必须要选个传输协议
> > 
> > 
> > vmess over tls就是協議vmess + 開啟tls
> 
> 你这等于没说

面板上的傳輸協議就是選vmess，下面的tls要enable
我想你是在面板設定內沒有加上"SSL 憑證檔案路徑"&"SSL 私鑰檔案路徑"
我只是針對你的問題回答，說話遣字不必如此
