### ISSUE TITLE
v4.24 版本起，每个 VMess 认证数据的服务器端结构都会包含一个一次写入的玷污状态标记

### ISSUE THREAD

**Issue by pbclaodentm** [sprov065/v2-ui#280]
VMessAEAD 头部加密实验 （公测阶段）
VMessAEAD 是用于对抗重放和读取长度探测的 VMess 协议的小修改，自 v4.24 版本起可以在客户端通过 testsEnabled 启用。在实验期间，需要客户端和服务器端版本相同。自 v4.24 版本起的服务器端自动启用本实验。本实验所采用的头部加密和认证有助于对抗基于抓包的重放攻击。启用本实验的客户端无法连接版本不匹配的服务器端。

在建立 VMess 连接时，启用了本实验的客户端会输出 "=======VMESSAEADEXPERIMENT ENABLED========"到命令行。本实验也可以通过设置环境变量 "VMESSAEADEXPERIMENT=y" 强制启用，"VMESSAEADEXPERIMENT=n" 强制禁用。

请反馈在实验中遇到的任何问题。

VMessAEAD 头部加密 将在公测结束后默认启用。届时服务器端将在有限的时间内默认保持对现有协议的兼容。
以上请大神及时更新，避免使用面板v2ray强制4.24以后启用后无法联通的后果

**Comment by sprov065** [comment]
这主要是需要客户端适配，服务端自动适应

**Comment by pbclaodentm** [comment]
最近v2ray升级挺频繁，主要是怕服务器升级后客户端连不上，这么说可以把v2-ui里的v2ray升级到最新都没问题么，不影响客户端连接
