### ISSUE TITLE
[feature]在mKCP传输选项中添加混淆密码项

### ISSUE THREAD

**Issue by EdChdX** [sprov065/v2-ui#283]
## 描述你想要的功能
如题。[KcpObject.seed](https://www.v2fly.org/chapter_02/transport/mkcp.html)

## 为何需要此功能
混淆mKCP连接，尽可能避免mKCP被识别。

## 其它说明
无。

**Comment by 0x0004** [comment]
@EdChdX 和伪装BT有什么不同？

**Comment by 0x0004** [comment]
@sprov065  今日更新V2rayN后，所有mkcp均不可用。求大佬尽快添加。
