### ISSUE TITLE
安装的时候会关闭防火墙，这个东西不能这样干啊，差点使我网关服务器挂了

### ISSUE THREAD

**Issue by canronglan** [sprov065/v2-ui#285]
close_firewall() {
    if [[ x"${release}" == x"centos" ]]; then
        systemctl stop firewalld
        systemctl disable firewalld
    elif [[ x"${release}" == x"ubuntu" ]]; then
        ufw disable
    elif [[ x"${release}" == x"debian" ]]; then
        iptables -P INPUT ACCEPT
        iptables -P OUTPUT ACCEPT
        iptables -P FORWARD ACCEPT
        iptables -F
    fi
}
我认为没有必要，你要安装，就把默认的65432端口加到允许端口后，这样的话把别人已经设置好的规则全部清空，这种操作真的很危险！

**Comment by uhFan-C** [comment]
搞得我ssh都连不上了

**Comment by 0x0004** [comment]
设计上应该考虑。
