### ISSUE TITLE
[feature]建议在帐号那页加一个实时显示流量的功能

### ISSUE THREAD

**Issue by christan-duplicate** [sprov065/v2-ui#298]
**提问须知**
在此统一说明一下，面板只是一个方便你配置 v2ray 的工具，v2ray 没有的功能面板也没有办法去配置，比如有人问我 ss 能不能加个混淆、能不能限制设备数/网速等等，这些功能 v2ray 是没有的。
我不是 v2ray 作者，这些核心的功能你得去找 v2ray，只有 v2ray 有了面板才能进行配置，链接在此：https://github.com/v2ray/v2ray-core/issues 。

**描述你想要的功能**
建议在帐号那页加一个实时显示流量的功能

**为何需要此功能**
就像首页显示cpu 内存一样的

**其它说明**

**Comment by sprov065** [comment]
首页就有
