### ISSUE TITLE
能提供一下源码吗？

### ISSUE THREAD

**Issue by softincl** [sprov065/v2-ui#299]
我想编译一个musl库版本的

**Comment by softincl** [comment]
> 我想编译一个musl库版本的

**Comment by softincl** [comment]
> 我想编译一个musl库版本的

**Comment by sprov065** [comment]
啥源码，v2-ui没有开源？

**Comment by softincl** [comment]
py?


---原始邮件---
发件人: &quot;sprov&quot;<notifications@github.com&gt;
发送时间: 2020年8月18日(周二) 晚上8:19
收件人: &quot;sprov065/v2-ui&quot;<v2-ui@noreply.github.com&gt;;
抄送: &quot;State change&quot;<state_change@noreply.github.com&gt;;&quot;softincl&quot;<2296428064@qq.com&gt;;
主题: Re: [sprov065/v2-ui] 能提供一下源码吗？ (#299)




 
啥源码，v2-ui没有开源？
 
&mdash;

**Comment by softincl** [comment]
没有编译方法？


---原始邮件---
发件人: &quot;sprov&quot;<notifications@github.com&gt;
发送时间: 2020年8月18日(周二) 晚上8:19
收件人: &quot;sprov065/v2-ui&quot;<v2-ui@noreply.github.com&gt;;
抄送: &quot;State change&quot;<state_change@noreply.github.com&gt;;&quot;softincl&quot;<2296428064@qq.com&gt;;
主题: Re: [sprov065/v2-ui] 能提供一下源码吗？ (#299)




 
啥源码，v2-ui没有开源？
 
&mdash;
