### ISSUE TITLE
[other]v2ray更新失败、错误日志不存在以及v2ray始终显示错误

### ISSUE THREAD

**Issue by colorfulshadowty** [sprov065/v2-ui#305]
问题详述：
###  1、官方v2ray已更新，脚本更新无法使用
```
ERROR: This script has been DISCARDED, please switch to fhs-install-v2ray project.
HOW TO USE: https://github.com/v2fly/fhs-install-v2ray
TO MIGRATE: https://github.com/v2fly/fhs-install-v2ray/wiki/Migrate-from-the-old-script-to-this

更新 v2ray 失败，请自行检查错误信息
```
###  2、使用新版本 v5.3.0 无法获取日志：
```
[root@oyi ~]# cat /etc/v2-ui/v2-ui.log

[root@oyi ~]#
```
###  3、面板始终显示`v2ray状态 错误`：在更新面板后发现无法使用v2ray，将面板以及v2ray全部卸载后，重新安装5.3.0面板以及官方新版v2ray。无论启用vmess还是vless均显示错误

系统：CentOS 7 : 4.12.10-1.el7.elrepo.x86_64

已有环境：nginx / 宝塔(端口均开，防火墙均关)

**Comment by sprov065** [comment]
修复

**Comment by hejie** [comment]
> 修复

根本没修复

**Comment by hejie** [comment]
> 修复
还是出现这个问题
![image](https://user-images.githubusercontent.com/661165/93289988-480af980-f812-11ea-9bfe-b04039cde6ee.png)

**Comment by DolorHunter** [comment]
旧的安装脚本已经弃用了, 现在用的是新的脚本. 查看上面给的 TO MIGRATE 的链接有迁移详细教程.
