### ISSUE TITLE
[BUG] 升级最新版内核不启动

### ISSUE THREAD

**Issue by yesmiley** [sprov065/v2-ui#312]
**描述你的问题**
从5.3.0-3 升级至5.4.0，目前v2ray内核启动失败（显示未运行）

**面板相关配置信息**
三个vmess，分别是tcp，ws，tcp，之前一直正常，未做任何修改

**面板是否正常运行**
正常

**与问题相关的面板日志及其他内容**
日志为空

**你所使用的面板版本**
5.4.0

**你所使用的系统（服务器）**
CentOS 7 x64

**你猜测可能的原因**
内核升级有问题

**Comment by sprov065** [comment]
尝试添加一个账号后再看

**Comment by yesmiley** [comment]
> 尝试添加一个账号后再看

能够添加成功，不过内核依然未运行

**Comment by yesmiley** [comment]
另外，尝试卸载并重装旧版本，也不正常，或许是旧版本所需的文件已经不见了？（我看安装日志里有两个文件显示notfound）

**Comment by sprov065** [comment]
不推荐再使用旧版本，v2ray未启动的原因可能是有端口被占用

尝试手动测试v2ray是否能正常启动：
/usr/local/v2-ui/bin/v2ray-v2-ui -config /usr/local/v2-ui/bin/config.json

**Comment by yesmiley** [comment]
只安装了v2-ui，端口监听检测也没有占用，应该可以排除。
手动测试报错是 `runtime: out of memory`

---
因为是专用机器没啥影响，所以暂时通过重装系统解决了，估计是前些天擅自运行官方新版内核脚本导致一些残余，也好，重装之后vless协议也不会报错了
