### ISSUE TITLE
[BUG]强烈建议恢复5.3.0-3 v2ray官方安装脚本，相比5.4.0和5.4.1这一版本是稳定可用的

### ISSUE THREAD

**Issue by Hikpy** [sprov065/v2-ui#319]
5.4.0，5.4.1自带v2ray 有问题，几个小时反复挂掉，重启面板恢复。

**Comment by sk007** [comment]
旧的内核没问题

**Comment by sk007** [comment]
新的 是有这个问题
比较麻烦

**Comment by 0x0004** [comment]
@Hikpy @sk007 什么环境，如何复现，我是5.2.1升上来，用了1小时暂时还没发现

**Comment by guanhemeng** [comment]
原官方脚本已弃用，且v2ray.com脱离控制后继续使用原官方脚本可能会造成一定的安全问题。
不建议恢复

**Comment by 0x0004** [comment]
> 原官方脚本已弃用，且v2ray.com脱离控制后继续使用原官方脚本可能会造成一定的安全问题。
> 不建议恢复

v2ray.com脱离控制是咋回事

**Comment by sk007** [comment]
希望可以先推出旧内核的 版本
在没解决掉线 问题之前！

**Comment by guanhemeng** [comment]
> > 原官方脚本已弃用，且v2ray.com脱离控制后继续使用原官方脚本可能会造成一定的安全问题。
> > 不建议恢复
> 
> v2ray.com脱离控制是咋回事

原开发者失踪，维护者没有足够权限（这也是v2fly存在的意义：V2ray原开发者因长期不上线，失去联络，新维护者不得不另起项目）
v2ray.com域名控制权不在v2fly团队手中。

**Comment by sprov065** [comment]
已更新，请测试一下

**Comment by jayvee902** [comment]
最新的5.4.3有问题，我使用的是谷歌云debian9，以前v2-ui的版本使用中，无论是ss 还是v2ray的utp都从来没出问题。直到更新到5.4.3，只剩下v2ray+ws+web尚可使用，其他的ss、v2ray的utp这两种方式，直接没了反应。强烈建议，一键安装中，提供版本回退或者选择安装版本。

**Comment by littlewhiteee** [comment]
Centos7系统安装  ，5.4.3 面板运行几分钟（10分钟以内）对用户的增删改查，禁用启用以及流量统计都会失效。请问怎么版本回退？应该回退到哪个版本？
