### ISSUE TITLE
[BUG]手动安装旧版本执行命令 chmod +x v2-ui bin/v2ray-v2-ui bin/v2ctl 出现以下提示 不能运行

### ISSUE THREAD

**Issue by sk007** [sprov065/v2-ui#323]
chmod: cannot access ‘bin/v2ray-v2-ui’: No such file or directory
chmod: cannot access ‘bin/v2ctl’: No such file or directory

**Comment by cnboy95** [comment]
我用Linux deploy的chroot容器搭建，报错Running in chroot, ignoring request.请问大佬怎么能解决

**Comment by sk007** [comment]
> 我用Linux deploy的chroot容器构造，报错在chroot中运行，忽略了请求。请问大佬怎么能解决

这个我就不知道了
