### ISSUE TITLE
使用一键脚本启动ws+tls但是v2ray始终启动失败

### ISSUE THREAD

**Issue by RachelLinke** [sprov065/v2-ui#327]
# 提问须知
 - 先仔细阅读博客文章及评论，查看是否有相关问题和解决方案，再查看所有 issues，包括已开启的和已关闭的，确认没有任何地方可以解决你的问题时再提问。
 - 如果是 v2ray 本身的问题，请找 v2ray 官方，而不是在这里问。
 - 如果是你自身的技术知识积累不够，例如 xxx 不会配置，xx 软件不会用，配置错误导致连不上等等问题。你可以换一个提问模板进行提问，而不是 BUG 反馈模板。此类问题我一般不会做回答，除非是有意义的问题。建议多学习相关技术，积累自身的技术水平。
 - 如果需要上传图片，直接将图片拖入此文本框即可。
 - 提问的艺术：https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md

**描述你的问题**
在使用该脚本时页面服务搭建成功，最初启用账户之前v2ray成功运行，后面完全失败，日志仅报告v2ray启动失败。

**面板相关配置信息**
使用的阿里云服务器，有域名且申请了FreeSSL的证书。

**面板是否正常运行**
仅v2ray启动失败。

**与问题相关的面板日志及其他内容**
V2Ray 4.27.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.6 linux/amd64)

A unified platform for anti-censorship.

main: failed to read config files: [/usr/local/v2-ui/bin/config.json] > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl:

v2ctl> Read config: /usr/local/v2-ui/bin/config.json

v2ray.com/core/infra/conf: Failed to build TLS config. > v2ray.com/core/infra/conf: failed to parse certificate > read /usr/src: is a directory > exit status 255

**你所使用的面板版本**
5.4.1

**你所使用的系统（服务器）**
CentOS 7

**你所使用的浏览器**
chrome
**你猜测可能的原因**

**Comment by RachelLinke** [comment]
这个是脚本无法生成配置文件么

**Comment by 932279632** [comment]
这个我遇到过，是我的TLS证书路径选的不对，直接复制证书和密钥内容后情动正常了。
