### ISSUE TITLE
远程DNS问题

### ISSUE THREAD

**Issue by Sky-public-cloud1** [sprov065/v2-ui#329]
使用V2UI搭建的V2ray程序，我发现在安卓上使用（v2ng）时候，就算全局+远程DNS为8.8.8.8，也是本地原生的DNS
Win（v2N）不开启自定义DNS表现同上，开启自定义后为自定义的dns

这个是v2-ui生成的vmess配置文件不够完善的原因吗

**Comment by sprov065** [comment]
可能是客户端实现的问题吧
