### ISSUE TITLE
[feature]面板显示和校准服务器时间的设置

### ISSUE THREAD

**Issue by qq3763** [sprov065/v2-ui#33]
**描述你想要的功能**
面板支持查看当前服务器的时间，以及手动调整或者NTP时间。

**为何需要此功能**
我使用CC的VPS，每次重启之后时间和正常时间相差大概5分钟，当V2ray不能使用的时候排查错误需要很多时间，因此还安装和一个linux面板用于调整时间。
如果v2ray有了面板处理时间问题的话，那很省事，也方便及时发现时间导致问题。
**其它说明**
感谢您一直都开发工作。

**Comment by sprov065** [comment]
这是你自己应该做的，这不是共性需求，自己设置一个自动同步时间的程序并不难，还有就是选择一个好的 VPS 提供商。

**Comment by qq3763** [comment]
好的，还是很谢谢你。
