### ISSUE TITLE
[other]可以提供v2ray-v2-ui的源码吗

### ISSUE THREAD

**Issue by cjcj5243** [sprov065/v2-ui#331]
通过面板设置v2ray后总是出现v2ray读取配置文件错误，希望开放v2ray-v2-ui的源码查一下问题。

**Comment by sprov065** [comment]
这就是官方v2ray内核，改了文件名而已

**Comment by cjcj5243** [comment]
> 这就是官方v2ray内核，改了文件名而已

是这样的，开启tls后，证书路径没有填写的话，会在config.json生成一个空的“certificate”（印象中是这个字段，记不清了）,这个导致v2ray读取配置文件错误，从config.json删掉这个就好了
