### ISSUE TITLE
[BUG]升级5.4之后运行一段时间端口无响应

### ISSUE THREAD

**Issue by fruit-forest** [sprov065/v2-ui#332]
v2-ui update升级5.4之后运行时间后频繁出现v2ray端口无响应，使用v2-ui status查看有如下警告。 

`
● v2-ui.service - v2-ui Service
   Loaded: loaded (/etc/systemd/system/v2-ui.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2020-09-10 13:19:05 EDT; 8h ago
 Main PID: 2695 (v2-ui)
   CGroup: /system.slice/v2-ui.service
           ├─2695 /usr/local/v2-ui/v2-ui
           ├─2696 /usr/local/v2-ui/v2-ui
           └─2701 /usr/local/v2-ui/bin/v2ray-v2-ui -config /usr/local/v2-ui/bin/config.json

Sep 10 22:10:15 fancy-hat-2.localdomain v2-ui[2695]: WARNING:root:v2ray api code 255
Sep 10 22:10:48 fancy-hat-2.localdomain v2-ui[2695]: WARNING:root:v2ray api code 255
Sep 10 22:11:21 fancy-hat-2.localdomain v2-ui[2695]: WARNING:root:v2ray api code 255
Sep 10 22:11:54 fancy-hat-2.localdomain v2-ui[2695]: WARNING:root:v2ray api code 255
Sep 10 22:12:27 fancy-hat-2.localdomain v2-ui[2695]: WARNING:root:v2ray api code 255
Sep 10 22:13:00 fancy-hat-2.localdomain v2-ui[2695]: WARNING:root:v2ray api code 255
Sep 10 22:13:33 fancy-hat-2.localdomain v2-ui[2695]: WARNING:root:v2ray api code 255
Sep 10 22:14:06 fancy-hat-2.localdomain v2-ui[2695]: WARNING:root:v2ray api code 255
Sep 10 22:14:39 fancy-hat-2.localdomain v2-ui[2695]: WARNING:root:v2ray api code 255
Sep 10 22:15:12 fancy-hat-2.localdomain v2-ui[2695]: WARNING:root:v2ray api code 255
`

**Comment by wopyai** [comment]
我目前也是5.4.1版本，用一会就会端口无响应

**Comment by wopyai** [comment]
但是查看v2-ui status，什么也不显示。

**Comment by sprov065** [comment]
已更新，请测试以一下

**Comment by Pezeo** [comment]
> 已更新，请测试一下

5.4.3依然存在此问题，正常工作一段时间后面板的资源占用监控和流量统计都不工作了。重启面板后恢复，过一段时间后又会再次卡住。面板卡住后v2ray正常运行，主要问题是卡住期间各用户的流量统计会丢失。

**Comment by Tao314** [comment]
今天刚装的，改端口就这个提示，麻烦大佬看下，原来的版本没这个问题，一直好好的

**Comment by uhFan** [comment]
我也是一样的问题

**Comment by Corpama** [comment]
可以通过该命令降级至5.4.0，已验证可通过5.4.3降级:
bash <(curl -Ls https://raw.githubusercontent.com/sprov065/v2-ui/master/install_new.sh) 5.4.0
