### ISSUE TITLE
V2Ray-Core升级了，现有的连接突然不好用了，v2-ui啥时候也同步升级一下v2内核？

### ISSUE THREAD

**Issue by Smilence-Maverick** [sprov065/v2-ui#334]
都是默认的情况，Windows上的V2RayN自动升级了内核，连接不上了。

附上部分log

2020/09/13 10:23:53 tcp:127.0.0.1:54512 accepted tcp:alive.github.com:443 [proxy] 
2020/09/13 10:23:53 tcp:127.0.0.1:54513 accepted tcp:[2606:4700:3034::681f:53d4]:443 [proxy] 
2020/09/13 10:23:53 tcp:127.0.0.1:54514 accepted tcp:autofillpasswordgen.asgfalcon.io:443 [proxy] 
2020/09/13 10:23:54 tcp:127.0.0.1:54517 accepted tcp:browser.pipe.aria.microsoft.com:443 [proxy] 
2020/09/13 10:23:55 tcp:127.0.0.1:54518 accepted tcp:www.youtube.com:443 [proxy] 
2020/09/13 10:23:55 tcp:127.0.0.1:54519 accepted tcp:api.webtest.net:443 [proxy] 
2020/09/13 10:23:55 tcp:127.0.0.1:54520 accepted tcp:www.youtube.com:443 [proxy] 
2020/09/13 10:23:58 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://AA.BB.CC:8443/aabbcc/): 404 Not Found > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
2020/09/13 10:23:59 tcp:127.0.0.1:54527 accepted tcp:www.youtube.com:443 [proxy] 
2020/09/13 10:23:59 tcp:127.0.0.1:54528 accepted tcp:www.youtube.com:443 [proxy] 
2020/09/13 10:23:59 tcp:127.0.0.1:54526 accepted tcp:browser.pipe.aria.microsoft.com:443 [proxy] 
2020/09/13 10:23:59 tcp:127.0.0.1:54529 accepted tcp:api.webtest.net:443 [proxy] 
2020/09/13 10:23:59 tcp:127.0.0.1:54530 accepted tcp:alive.github.com:443 [proxy] 
2020/09/13 10:23:59 tcp:127.0.0.1:54531 accepted tcp:autofillpasswordgen.asgfalcon.io:443 [proxy] 
2020/09/13 10:24:01 tcp:127.0.0.1:54534 accepted tcp:alive.github.com:443 [proxy] 
2020/09/13 10:24:06 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://AA.BB.CC:8443/aabbcc/): 404 Not Found > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
2020/09/13 10:24:07 tcp:127.0.0.1:54543 accepted tcp:alive.github.com:443 [proxy] 
2020/09/13 10:24:07 tcp:127.0.0.1:54545 accepted tcp:www.youtube.com:443 [proxy] 
2020/09/13 10:24:09 tcp:127.0.0.1:54548 accepted tcp:[2606:4700:3034::681f:53d4]:443 [proxy] 
2020/09/13 10:24:09 tcp:127.0.0.1:54549 accepted tcp:www.youtube.com:443 [proxy] 
2020/09/13 10:24:11 tcp:127.0.0.1:54551 accepted tcp:browser.pipe.aria.microsoft.com:443 [proxy] 
2020/09/13 10:24:14 tcp:127.0.0.1:54552 accepted tcp:alive.github.com:443 [proxy] 
2020/09/13 10:24:16 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://AA.BB.CC:8443/aabbcc/): 404 Not Found > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
2020/09/13 10:24:17 tcp:127.0.0.1:54554 accepted tcp:browser.pipe.aria.microsoft.com:443 [proxy] 
2020/09/13 10:24:17 tcp:127.0.0.1:54555 accepted tcp:www.youtube.com:443 [proxy] 
2020/09/13 10:24:17 tcp:127.0.0.1:54557 accepted tcp:www.youtube.com:443 [proxy] 
2020/09/13 10:24:17 tcp:127.0.0.1:54556 accepted tcp:alive.github.com:443 [proxy] 
2020/09/13 10:24:17 tcp:127.0.0.1:54558 accepted tcp:[2606:4700:3034::681f:53d4]:443 [proxy] 
2020/09/13 10:24:19 tcp:127.0.0.1:54562 accepted tcp:g.api.mega.co.nz:443 [proxy]

**Comment by guanhemeng** [comment]
可以下载v2fly的release手动替换二进制文件，之后不要选择脚本中的更新v2-ui选项，它会将核心替换为仓库内的旧版本（目前仓库里是4.27.0）

**Comment by ajiou** [comment]
4.27 跟 4.28 中的 fallback 设定不太一样，还需要改config.json的内容

**Comment by sprov065** [comment]
已更新
