### ISSUE TITLE
[BUG]面板启动后一段时间无响应

### ISSUE THREAD

**Issue by 17665347409** [sprov065/v2-ui#340]
**描述你的问题**
>启动一段时间后就无响应了，包括流量统计和各种信息

**面板相关配置信息**
>无

**面板是否正常运行**
>提示：systemctl status v2-ui -l

**与问题相关的面板日志及其他内容**
>提示：cat /etc/v2-ui/v2-ui.log

**你所使用的面板版本**
5.4.3

**你所使用的系统（服务器）**
CentOS7

**你所使用的浏览器**
Chrome

**你猜测可能的原因**
不知道

**Comment by Greeed-islanl** [comment]
在ssh下重启 面板就ok了

**Comment by 17665347409** [comment]
> 在ssh下重启 面板就ok了

这是没有办法的办法 几乎每隔一两个小时就要重启一次 经常还会有端口假死 流量统计也会失效

**Comment by uhFan** [comment]
我最近更新后也是经常遇到

**Comment by 17665347409** [comment]
> 我最近更新后也是经常遇到

我现在也是只能crontab设置半个小时重启一次

**Comment by sprov065** [comment]
已更新
