### ISSUE TITLE
[BUG] 关于kcp的密码

### ISSUE THREAD

**Issue by yesmiley** [sprov065/v2-ui#345]
请问为何在选择 kcp 协议之后，会有一项【密码】？
我的客户端上并没有这个选项，这导致我的 vless-kcp 无法连接

**Comment by ZhangSir9901** [comment]
这个密码无需理会。新增客户会出现问题。等待版本升级后修复。

**Comment by yesmiley** [comment]
@ZhangSir9901 难怪呢，好吧，我先用 vless-tcp 了，谢谢

**Comment by sprov065** [comment]
v2ray的kcp配置有变，请前往v2ray官方文档查看说明
