### ISSUE TITLE
[other]为什么我选kcp的话就无法连接？防火墙端口都开了

### ISSUE THREAD

**Issue by ltynaive** [sprov065/v2-ui#346]
![image](https://user-images.githubusercontent.com/28057220/94096849-b4f84200-fe57-11ea-983c-3d9cacef3bcc.png)
![image](https://user-images.githubusercontent.com/28057220/94096861-baee2300-fe57-11ea-8d55-3e652940b0c7.png)

选tcp的话就能使用，选kcp的话，端口就ping不通，v2ray也连不上。系统都是全新安装的，不知道为啥...求指教

**Comment by Surface0Tension** [comment]
因为kcp走的是udp协议，你要看你在防火墙里有没有开放对应的udp端口

**Comment by sprov065** [comment]
v2ray的kcp配置有变，请前往v2ray官方文档查看说明
