### ISSUE TITLE
[feature]新版本的两个功能建议

### ISSUE THREAD

**Issue by ZhangSir9901** [sprov065/v2-ui#348]
**功能建议一：**

新开用户可以设置用户的限制分为两个开关；

时长控制开关和流量控制开关。

比如新增某一个用户，
设定使用时长为一个月，那么到期后账号自动停用；
设定使用流量总量为10G，那么流量满额后账号自动停用；

这两个开关可以同时开启，不管哪个条件达到，都自动停用账号。

**功能建议二：**

对账号的新增和停用，可以发送邮件提醒。

**Comment by sprov065** [comment]
不会增加
