### ISSUE TITLE
[BUG]5.4.3流量不统计了。不能统计流量 了。

### ISSUE THREAD

**Issue by hero3320** [sprov065/v2-ui#350]
今天安装了5.4.3版本，流量统计功能失效！！！！！

**Comment by ZehuanZhang** [comment]
同样的问题

**Comment by qaxc** [comment]
面板开启一段时间后所有功能会失效，只有重启才会正常，但是过段时间又失效，所以统计流量功能等于报废了

**Comment by Lonlykids** [comment]
@qaxc @ZehuanZhang @hero3320 估计你们用手机打开过或者在PC转成mobile模式打开过Dashboard , 不打开的话估计没啥事..

**Comment by ZehuanZhang** [comment]
> @qaxc @ZehuanZhang @hero3320 估计你们用手机打开过或者在PC转成mobile模式打开过Dashboard , 不打开的话估计没啥事..

不好意思，没有使用过mobile模式，都是直接电脑上操作的，流量统计功能的确不正常，及时重启dashboard也是一样会有问题

**Comment by TIANQIANgGZ** [comment]
> 今天安装了5.4.3版本，流量统计功能失效！！！！！

降到5.4.1版本就好了

**Comment by xuexiaokang** [comment]
确实同样的问题

**Comment by sprov065** [comment]
已修复
