### ISSUE TITLE
面板开启一段时间后统计功能会失效，只有重启才会正常，但是过段时间又失效

### ISSUE THREAD

**Issue by pangci22** [sprov065/v2-ui#352]
如题，版本5.4.3，v2版本4.28.1，系统debian10。

所有统计功能失效，例如主页面的系统状态，账号列表的里的账户流量统计。
但v2是正常的可以使用。
![image](https://user-images.githubusercontent.com/45974159/94643304-11a4a280-0319-11eb-917a-f56784f1d387.png)

**Comment by jhsb** [comment]
同样问题，请求修复

**Comment by pudding1111** [comment]
主界面的一切信息都卡住了，重启解决，过一段时间复现。
