### ISSUE TITLE
面板启动成功后没有创建日志文件

### ISSUE THREAD

**Issue by Kannnnng** [sprov065/v2-ui#357]
**描述你的问题**
>面板启动成功后没有创建日志文件，导致无法查看面板运行日志。

**面板相关配置信息**
>![image](https://user-images.githubusercontent.com/22359680/95539738-c0379a00-0a21-11eb-96d9-8df028075a56.png)

**面板是否正常运行**
>面板显示运行正常。

**你所使用的面板版本**
5.4.4

**你所使用的系统（服务器）**
debian-10-x86_64

**你所使用的浏览器**
Google Chrome 84

**Comment by Kannnnng** [comment]
我了解到可以使用v2ray自带的日志功能，并能够通过面板设置中的v2ray配置模板一栏来开启日志功能并指定日志文件所在位置，这已经能够解决我的问题，但v2-ui本身的日志功能我仍然不知道如何开启，对应的日志文件也不存在。

我写下上面的内容是希望能够帮助跟我遇到了相同问题的人。

**Comment by tobywing** [comment]
我也碰到这样的问题，请问应该怎么解决？谢谢

**Comment by sprov065** [comment]
没有日志说明没有问题，不需要关心
