### ISSUE TITLE
[feature] Limit number of devices or IPs

### ISSUE THREAD

**Issue by hybtoy** [sprov065/v2-ui#36]
**Describe the features you want**
Limit number of devices. 1 account(port) = 1 IP = 1 device

**Why do you need it**
Users will not re-share their accounts.

**other description**
Thanks for such a great panel.
Well done!

**Comment by sprov065** [comment]
You should go to the v2ray official and let them implement this feature.

**Comment by hybtoy** [comment]
@sprov065 
I think it could be implemented with iptables. Example:
`iptables -A INPUT -p tcp --syn -dport 34333 -m iplimit --iplimit-above 3 -J REJECT`

Can we do this through the panel?
