### ISSUE TITLE
账号删除后虽然不能使用.但是还能正常ping通.

### ISSUE THREAD

**Issue by littlewhiteee** [sprov065/v2-ui#360]
当前面板版本5.4.4 

将面板的一个用户删除后,虽然该用户不能再使用该节点,但是在Shadowrocket上还能正常ping通服务器?希望设计成之前版本一样.不能使用后就显示为"超时".

**Comment by Corpama** [comment]
先确认一下你的shaodowrocket延迟测试方法的方式是否为icmp，该测试方法通过ping 服务器ip的方式测试延迟，这是肯定可以正常ping通的
