### ISSUE TITLE
配置反向代理后面板数据全是缓存

### ISSUE THREAD

**Issue by huangying10000** [sprov065/v2-ui#362]
配置反向代理

![image](https://user-images.githubusercontent.com/44154448/96662661-6324d800-1381-11eb-8470-39b378d53cb7.png)

这个接口数据全是缓存
![image](https://user-images.githubusercontent.com/44154448/96662755-a41cec80-1381-11eb-85cd-5c44b1ccae6f.png)

**Comment by sprov065** [comment]
跟面板无关
