### ISSUE TITLE
[feature] 优化端口冲突的检测机制

### ISSUE THREAD

**Issue by yesmiley** [sprov065/v2-ui#363]
**描述你想要的功能**
当冲突端口所在配置为`关闭`状态时，允许添加相同的端口

**为何需要此功能**
使添加相同端口配置进行测试更加方便。
目前是直接禁止与已有端口相同的配置去创建，这使得要创建新配置就必须改变原有配置的端口为另外一个，即使是在另一个配置为`关闭`状态时依然如此。

**Comment by sprov065** [comment]
数据库的 port 是 unique 的，不能有相同的端口号
