### ISSUE TITLE
[feature]系统状态页面显示当前 v2ray-core 版本

### ISSUE THREAD

**Issue by yuangezhizao** [sprov065/v2-ui#369]
> **提问须知**
在此统一说明一下，面板只是一个方便你配置 v2ray 的工具，v2ray 没有的功能面板也没有办法去配置，比如有人问我 ss 能不能加个混淆、能不能限制设备数/网速等等，这些功能 v2ray 是没有的。
我不是 v2ray 作者，这些核心的功能你得去找 v2ray，只有 v2ray 有了面板才能进行配置，链接在此：https://github.com/v2ray/v2ray-core/issues 。

**描述你想要的功能**
看到`/server/status`这个`api`下返回了`v2`的版本：`version: "4.32.0"`

**为何需要此功能**
但是系统状态页面中并没有实际的位置来显示这个值，每次想查看当前生效版本都得`F12`

**其它说明**
thanks

**Comment by NeptuneIsTheBest** [comment]
v2ray-core的版本可以在设置页面中看到，

我觉得不合理的是更换Core版本的按钮和显示Core版本不在一个页面内

**Comment by yuangezhizao** [comment]
> v2ray-core的版本可以在设置页面中看到，
> 
> 我觉得不合理的是更换Core版本的按钮和显示Core版本不在一个页面内

才想起来放在了这个位置上，不过还是不方便（

**Comment by NeptuneIsTheBest** [comment]
确实是不方便，每次切换完都要去看一下当前是哪个版本在生效😂

**Comment by liuxyon** [comment]
是的应该改到主页

**Comment by yuangezhizao** [comment]
感谢作者实装（
https://github.com/sprov065/v2-ui/releases/tag/5.4.6
