### ISSUE TITLE
[feature]建议增加 IPv6 的监听

### ISSUE THREAD

**Issue by chrisxvin** [sprov065/v2-ui#37]
sprov-ui 默认是能从 ipv6 端口访问的，v2 就不行。手动修改监听地址为 [::]，面板就起不起来了。

希望能支持绑定 ipv6 的端口。

**Comment by sprov065** [comment]
两个面板在这个功能上没有区别，只有可能你自己弄错了

**Comment by sprov065** [comment]
你指的是网页访问吧，我还以为你说的v2ray监听地址，这个我倒是没有试过，以后看看能不能改改吧

**Comment by sprov065** [comment]
面板设置里监听IP设置为空即可同时监听IPv4和v6
