### ISSUE TITLE
[feature]能否增加v2ray连接的ip信息，以便不定时查看封锁滥用者或者不被允许使用者？

### ISSUE THREAD

**Issue by chaosye0** [sprov065/v2-ui#370]
**描述你想要的功能**
能否在面板流量统计那里增加v2ray连接的ip信息，以便不定时查看封锁滥用者或者不被允许使用者？

**为何需要此功能**
便于管理一些滥用的用户吧，因为是合租机子，这样能查看的话方便管理

**其它说明**

**Comment by ZhangSir9901** [comment]
目前没有这个功能。只能通过流量来卡。

**Comment by NeptuneIsTheBest** [comment]
这个可以在v2的日志里发现 你可以利用iptabls之类的来ban掉IP
