### ISSUE TITLE
能否添加一个计划任务

### ISSUE THREAD

**Issue by dakezuo** [sprov065/v2-ui#373]
**提问须知**
在此统一说明一下，面板只是一个方便你配置 v2ray 的工具，v2ray 没有的功能面板也没有办法去配置，比如有人问我 ss 能不能加个混淆、能不能限制设备数/网速等等，这些功能 v2ray 是没有的。
我不是 v2ray 作者，这些核心的功能你得去找 v2ray，只有 v2ray 有了面板才能进行配置，链接在此：https://github.com/v2ray/v2ray-core/issues 。

**描述你想要的功能**
能否添加一个计划任务，定时比对v2ray内核版本，并升级至最新版本

**为何需要此功能**
有时候会出现断流情况，不知道是否新的内核会有优化，又不知道何时发布了新内核，如果能提供一个定时对比并升级的功能，那最好不过了，可以保证vps上的内核一直是最新的

**其它说明**

**Comment by sprov065** [comment]
自动更新v2ray内核可能会导致新版v2ray配置不兼容等问题，面板已经提供了手动选择版本的选项
