### ISSUE TITLE
[other] v2ray-core版本问题

### ISSUE THREAD

**Issue by lijingchun0** [sprov065/v2-ui#382]
目前看最新的v2ray-core 版本是4.31.0 但是面板中显示最新的是4.33.0  
![image](https://user-images.githubusercontent.com/26979634/100430129-4b9fe400-30d1-11eb-822f-4fb66fa928c9.png)
![image](https://user-images.githubusercontent.com/26979634/100430139-522e5b80-30d1-11eb-9c40-e7bc38ba7bc2.png)

**Comment by ZhangSir9901** [comment]
![image](https://user-images.githubusercontent.com/61982202/100437390-a2122000-30db-11eb-9ba6-4be272a883f1.png)
https://github.com/v2fly/v2ray-core
你确认你眼睛没有问题？！

**Comment by lijingchun0** [comment]
> ![image](https://user-images.githubusercontent.com/61982202/100437390-a2122000-30db-11eb-9ba6-4be272a883f1.png)
> https://github.com/v2fly/v2ray-core
> 你确认你眼睛没有问题？！

看成 这个了。。。。 
https://github.com/v2ray/v2ray-core
