### ISSUE TITLE
[other]架设面板之后，第二天VPS受到攻击，可能会是哪个环节的问题呢？

### ISSUE THREAD

**Issue by fhzheng** [sprov065/v2-ui#383]
11.26晚上我在自己的VPS上架设了v2-ui，改了密码，使用NGINX映射到外网，同时用了Let's Encrypt的HTTPS证书。27号上午收到了VPS提供商的通知，说我的服务器因为用于DoS攻击，所以被强制停止了。
![微信图片_20201130105827](https://user-images.githubusercontent.com/3986355/100564105-02cb7380-32fb-11eb-9982-9fc755ecf001.png)
由于本人在网安方面是完全的小白，没有进一步调查的信息，之后把VPS机器重置后继续正常使用了。
但是在26号的操作之前很久（>3个月），除了日常升级yum，没有对VPS进行任何大的操作。根据这个时间点的关联性感觉有些蹊跷。
声明：在此没有指责的意思，只是希望开发和使用人员可以关注一下项目中可能的安全问题，防患于未然。

**Comment by sprov065** [comment]
自行加强 ssh 防范，可能被爆破，攻击者再怎么样也不可能通过 v2-ui 来控制 vps
