### ISSUE TITLE
请教一下有关面板默认显示页面问题

### ISSUE THREAD

**Issue by calonye** [sprov065/v2-ui#387]
目前我修改了根目录，所以在访问一级地址时，此时浏览器就报404，这是正常的，毕竟我修改了根目录，得通过完整的地址来访问。

但是想请问，我想做个404的页面放在这个位置里，找了一遍，没找到应该放哪里，例如我丢在「/usr/local/v2-ui/templates/」根目录下，但实际并没有生效的。

想请问一下，这种情况，应该将404页放在v2-ui的哪个目录下才会生效，还是或它其实并没有走向到v2-ui根目录，而是ng？

**Comment by sprov065** [comment]
你只能通过修改python代码来实现
