### ISSUE TITLE
kcp账号不能正常启动

### ISSUE THREAD

**Issue by qian9008** [sprov065/v2-ui#388]
tcp账号正常，kcp  quic 账号设置后查看端口 没有被占用

**Comment by ZhangSir9901** [comment]
kcp不能使用很久了。凡是带密码的协议都不能使用。不知道怎么设置和操作。也找不到教程。

**Comment by nicolas772580** [comment]
俺也一样

**Comment by ZhangSir9901** [comment]
> 俺也一样

哈哈哈哈哈。画面感十足。

**Comment by 0x0004** [comment]
这个是最完美的搭配，兼容性最佳没有之一。缺点是不支持kcp seed，不过稳就完事了。
当前面板版本 | 5.4.1
V2ray 内核版本 | 4.27.0
@qian9008 
@ZhangSir9901 
@nicolas772580

**Comment by sprov065** [comment]
修复kcp seed未设置在vmess链接中的问题
