### ISSUE TITLE
[other]配置了证书和域名,设置443端口，为何不能创建多个账号？

### ISSUE THREAD

**Issue by shibowe** [sprov065/v2-ui#389]
用ws+tls方式，创建多账号的情况下，端口随机，证书是通配符的格式，
为何链接失败？

目前成功的一个账号是：
主域名+证书+开443端口 .

如果我想创建a.domain.com , b.domain.com ,
具体的配置和证书，也可以用原来的么？

**Comment by ZehuanZhang** [comment]
WS+TLS应该只能一个端口服务一个账号，如果要一个端口多个账号，可以使用WS+TLS+Web，具体可参考：
https://toutyrater.github.io/advanced/wss_and_web.html
这样的话需要额外配置Web的转发规则，祝好。

**Comment by ZehuanZhang** [comment]
证书如果是通配证书，三级域名不会影响，如果证书只针对特定域名a.*.*签发，b.*.*的安全验证就会受到影响

**Comment by shibowe** [comment]
> 证书如果是通配证书，三级域名不会影响，如果证书只针对特定域名a.*.* 签发，b.*.* 的安全验证就会受到影响
用了多端口的方法解决了。
感谢。
