### ISSUE TITLE
[feature]建议允许在一个端口下添加多个使用相同协议的用户

### ISSUE THREAD

**Issue by SteamSnake** [sprov065/v2-ui#39]
现在的v2-ui可能是为了方便不同用户使用不同协议，强制要求添加的用户都为不同端口。但实际上使用相同协议，只有uuid不同的用户可以共用一个端口，而不同用户的流量统计可以根据不同的email名称来统计。

**Comment by sprov065** [comment]
设计已经定下来了，无法更改

**Comment by Deguang** [comment]
针对cdn的场景，无法共享端口，就无法实现简单的多用户管理 [头疼]
