### ISSUE TITLE
[feature]请求添加socks5 + ws

### ISSUE THREAD

**Issue by TXIuTnVsbA** [sprov065/v2-ui#390]
我发现ui只支持到shadowsocks + ws
但v2ray原版已经可以socks5 + ws了
所以我想添加这个东西，但是自己又不会搞，只能拜托作者了

**Comment by TXIuTnVsbA** [comment]
这个组合估计占用cpu非常的小，安全性的话，因为是ws + tls 所以你懂的

**Comment by sprov065** [comment]
很奇葩的配置，不太现实
