### ISSUE TITLE
[other]彩蛋是什么啊

### ISSUE THREAD

**Issue by imzrme** [sprov065/v2-ui#405]
找到了彩蛋，没看懂
![Screenshot_2021-01-20-10-20-35-260_com server auditor ssh client](https://user-images.githubusercontent.com/62274834/105119721-db7b7080-5b0b-11eb-8396-c7a06452a298.jpg)

**Comment by sprov065** [comment]
我也没懂

**Comment by imzrme** [comment]
> 我也没懂
这不是你写的吗
