### ISSUE TITLE
x-ray 支持

### ISSUE THREAD

**Issue by testermania** [sprov065/v2-ui#420]
xray 支持

xray core 1.3.0

Milestone
至此，Xray-core 实现了全软件全协议全出入站全传输方式的全面 FullCone，这是一个里程碑式的成就：

无论你在用 VLESS/VMess/Mux/Trojan/Shadowsocks，无论你选择 XTLS/KCP/CDN/H2/QUIC，无论 Socks 还是 TPROXY... 全部 FullCone

FullCone 不再是哪个协议的专利，它已经像空气一样自然，随处可见，不留任何遗憾。

**Comment by jamespan2012** [comment]
期待更新，多谢大佬

**Comment by zzx396** [comment]
自行下载xray内核，更换/usr/local/v2-ui/bin下的v2ray-v2-ui文件即可。

**Comment by sprov065** [comment]
已更新
