### ISSUE TITLE
[other]Google Play 不能下载及更新

### ISSUE THREAD

**Issue by SpaceTimer** [sprov065/v2-ui#421]
安装完成，可以访问管理网页，功能都没有问题。
Android手机可以访问Google Play， 唯独不能从Google Play下载及更新， 请问可能会是什么情况？

**Comment by ramocky** [comment]
> 安装完成，可以访问管理网页，功能都没有问题。
> Android手机可以访问Google Play， 唯独不能从Google Play下载及更新， 请问可能会是什么情况？

没有内置gms？
