### ISSUE TITLE
希望能增加一个显示生成的账号被几个终端使用并限制终端数

### ISSUE THREAD

**Issue by xuexiaokang** [sprov065/v2-ui#424]
**提问须知**
在此统一说明一下，面板只是一个方便你配置 v2ray 的工具，v2ray 没有的功能面板也没有办法去配置，比如有人问我 ss 能不能加个混淆、能不能限制设备数/网速等等，这些功能 v2ray 是没有的。
我不是 v2ray 作者，这些核心的功能你得去找 v2ray，只有 v2ray 有了面板才能进行配置，链接在此：https://github.com/v2ray/v2ray-core/issues 。

**描述你想要的功能**
希望能增加一个显示生成的账号被几个终端使用并限制终端数

**为何需要此功能**
生成的账号出现流量跑得特别大，怀疑是被人盗用了，否则一个终端产生不了那么大流量，所以希望能增加显示这个账号被几个终端使用，同时能够限制一个账号最多几个终端使用

**其它说明**

**Comment by 451328707** [comment]
这个服务器本来就是只通过用户名来验证，不可能知道终端有几个
