### ISSUE TITLE
[BUG]VLESS分享链接无备注

### ISSUE THREAD

**Issue by GhostHjh** [sprov065/v2-ui#429]
**描述你的问题**
>VLESS分享的链接没有备注

**面板相关配置信息**
>面板运行一切正常

**面板是否正常运行**
>正常

**与问题相关的面板日志及其他内容**
>v2-ui分享出来的链接
>```
>vless://b1439346-bb24-498d-87d0-824f635dd175@[2a02:180:6:1::28e6]:56788?type=tcp&security=none
>```
>我在v2-ui创建的这个分享链接的备注为'测试'
>理论上正确的分享链接
>```
>vless://b1439346-bb24-498d-87d0-824f635dd175@[2a02:180:6:1::28e6]:56788?encryption=none&security=none&type=tcp&headerType=none#%e6%b5%8b%e8%af%95
>```

**你所使用的面板版本**
>最新版

**你所使用的系统(服务器)**
>Debian 10 

**你所使用的浏览器**
>Chrome 89.0.4389.72（正式版本） （64 位）

**你猜测可能的原因**
>v2-ui最后一次更新时还没有这个vless链接分享标准出来(大概吧)

**Comment by sprov065** [comment]
5.5.0已加上
