### ISSUE TITLE
[feature]希望可以增添自定义服务器地址功能

### ISSUE THREAD

**Issue by gongyc** [sprov065/v2-ui#43]
因为服务器用nginx绑定了域名，如果用面板自动生成的链接，里面的服务器地址是我vps的ip，但是更加希望可以更改成自定义的域名~
例如（解码后）
{
  "v": "2",
  "ps": "Slakey_Rent2",
  "add": "www.baidu.com",
  "port": 2222,
  "id": "sdfsfsded-sdfd-sdfs-sdfs-sdfsdfsdffsd",
  "aid": 64,
  "net": "ws",
  "type": "none",
  "host": "",
  "path": "/rent2",
  "tls": "none"

**Comment by sprov065** [comment]
自己在客户端改一下就行了，或者用域名访问面板

**Comment by gongyc** [comment]
感谢~用域名访问就可以了！
