### ISSUE TITLE
[BUG]重启面板后,确认过快导致v2ray状态显示异常

### ISSUE THREAD

**Issue by GhostHjh** [sprov065/v2-ui#433]
**描述你的问题**
>重启v2-ui面板后,如果在回车返回菜单时过快会导致的第一次显示v2ray状态为未运行
>![image](https://user-images.githubusercontent.com/56105932/110448272-ff1a6a80-80fb-11eb-9f69-48e66a1e38aa.png)
>重新查看即为为正常

**面板相关配置信息**
>无

**面板是否正常运行**
>正常

**与问题相关的面板日志及其他内容**
>无

**你所使用的面板版本**
最新版

**你所使用的系统（服务器）**
Centos 7 x64

**你所使用的浏览器**
Chrome

**你猜测可能的原因**
面板重启后,显示"按回车返回主菜单:"前,只做了面板运行判断,未做v2ray运行判断,而有的小鸡v2ray运行缓慢,导致v2-ui第一时间以为v2ray未运行

**Comment by sprov065** [comment]
这个无伤大雅
