### ISSUE TITLE
新版本的如何手动安装, 教程貌似过时了,麻烦更新下教程

### ISSUE THREAD

**Issue by xman55555** [sprov065/v2-ui#442]
手动安装教程和 最新版本不兼容

**Comment by Ningzetao** [comment]
/usr/bin/v2-ui:行7: 未预期的符号 `newline' 附近有语法错误
/usr/bin/v2-ui:行7: `<!DOCTYPE html>'

**Comment by andfk44** [comment]
安装正常的，https://github.com/sprov065/v2-ui/releases/tag/5.5.0
手动安装 v2-ui
https://github.com/sprov065/v2-ui/releases/tag/5.1.2
从该地址中下载最新的 v2-ui-linux.tar.gz 文件，并上传至 VPS 的 /root/ 目录下。若你上传至其它的目录，则将第一行命令的 cd /root/ 改为 cd [实际的目录]，不用包括文件名。
cd /root/
mv v2-ui-linux.tar.gz /usr/local/
cd /usr/local/
tar zxvf v2-ui-linux.tar.gz
rm v2-ui-linux.tar.gz -f
cd v2-ui
chmod +x v2-ui bin/xray-v2-ui
cp -f v2-ui.service /etc/systemd/system/
systemctl daemon-reload
systemctl enable v2-ui
systemctl restart v2-ui
 
curl -o /usr/bin/v2-ui -Ls https://raw.githubusercontent.com/sprov065/v2-ui/master/v2-ui.sh
chmod +x /usr/bin/v2-ui
