### ISSUE TITLE
[BUG]适配ARM平台

### ISSUE THREAD

**Issue by samleong123** [sprov065/v2-ui#466]
# 提问须知
 - 先仔细阅读博客文章及评论，查看是否有相关问题和解决方案，再查看所有 issues，包括已开启的和已关闭的，确认没有任何地方可以解决你的问题时再提问。
 - 如果是 v2ray 本身的问题，请找 v2ray 官方，而不是在这里问。
 - 如果是你自身的技术知识积累不够，例如 xxx 不会配置，xx 软件不会用，配置错误导致连不上等等问题。你可以换一个提问模板进行提问，而不是 BUG 反馈模板。此类问题我一般不会做回答，除非是有意义的问题。建议多学习相关技术，积累自身的技术水平。
 - 如果需要上传图片，直接将图片拖入此文本框即可。
 - 提问的艺术：https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md

**描述你的问题**
>请尽可能的精确描述你的问题，尽量不要使用笼统的词汇。
适配ARM平台,Ampere CPU

**面板相关配置信息**
>提供与问题相关的面板账号信息截图，面板设置截图，v2ray config.json 内容等，自行打码敏感信息
启动提示错误 , Status也提示如下错误:

```
● v2-ui.service - v2-ui Service
     Loaded: loaded (/etc/systemd/system/v2-ui.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2021-05-26 18:42:39 +08; 17s ago
    Process: 562963 ExecStart=/usr/local/v2-ui/v2-ui (code=exited, status=203/EXEC)
   Main PID: 562963 (code=exited, status=203/EXEC)
May 26 18:42:39 instance-20210526-1618 systemd[1]: Started v2-ui Service.
May 26 18:42:39 instance-20210526-1618 systemd[562963]: v2-ui.service: Failed to execute command: Exec format error
May 26 18:42:39 instance-20210526-1618 systemd[562963]: v2-ui.service: Failed at step EXEC spawning /usr/local/v2-ui/v2-ui: Exec format error
May 26 18:42:39 instance-20210526-1618 systemd[1]: v2-ui.service: Main process exited, code=exited, status=203/EXEC
May 26 18:42:39 instance-20210526-1618 systemd[1]: v2-ui.service: Failed with result 'exit-code'. 
```

**面板是否正常运行**
>提示：systemctl status v2-ui -l
不,提示如下错误
```
● v2-ui.service - v2-ui Service
     Loaded: loaded (/etc/systemd/system/v2-ui.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2021-05-26 18:42:39 +08; 17s ago
    Process: 562963 ExecStart=/usr/local/v2-ui/v2-ui (code=exited, status=203/EXEC)
   Main PID: 562963 (code=exited, status=203/EXEC)

May 26 18:42:39 instance-20210526-1618 systemd[1]: Started v2-ui Service.
May 26 18:42:39 instance-20210526-1618 systemd[562963]: v2-ui.service: Failed to execute command: Exec format error
May 26 18:42:39 instance-20210526-1618 systemd[562963]: v2-ui.service: Failed at step EXEC spawning /usr/local/v2-ui/v2-ui: Exec format error
May 26 18:42:39 instance-20210526-1618 systemd[1]: v2-ui.service: Main process exited, code=exited, status=203/EXEC
May 26 18:42:39 instance-20210526-1618 systemd[1]: v2-ui.service: Failed with result 'exit-code'.

```
**与问题相关的面板日志及其他内容**
>提示：cat /etc/v2-ui/v2-ui.log
No such file or directory

**你所使用的面板版本**
最新版本

**你所使用的系统（服务器）**
ARM based Ampere CPU , 甲骨文

**你所使用的浏览器**
Microsoft Edge

**你猜测可能的原因**
不适配ARM

**Comment by zzx396** [comment]
果然是薅甲骨文的同党，哈哈哈！我搜了下说安装python3和依赖就能用了。

**Comment by simplove** [comment]
arm平台无论是一键脚本，还是手动安装，程序都跑不起来。
 
面板状态: 未运行
是否开机自启: 是
xray 状态: 未运行

请输入选择 [0-14]: 10
● v2-ui.service - v2-ui Service
   Loaded: loaded (/etc/systemd/system/v2-ui.service; enabled; vendor preset: disabled)
   Active: failed (Result: core-dump) since Thu 2021-05-27 06:10:50 GMT; 2h 24min ago
  Process: 76525 ExecStart=/usr/local/v2-ui/v2-ui (code=dumped, signal=SEGV)
 Main PID: 76525 (code=dumped, signal=SEGV)

5月 27 06:10:49 JP-3 systemd[1]: Started v2-ui Service.
5月 27 06:10:50 JP-3 systemd[1]: v2-ui.service: Main process exited, code=dumped, status=11/SEGV
5月 27 06:10:50 JP-3 systemd[1]: v2-ui.service: Failed with result 'core-dump'.

请输入选择 [0-14]: 7
面板启动失败，可能是因为启动时间超过了两秒，请稍后查看日志信息

**Comment by samleong123** [comment]
![image](https://user-images.githubusercontent.com/58818070/119831670-15cca280-bf30-11eb-9ad5-0504c76e41dc.png)
适配了~

**Comment by simplove** [comment]
你这是ubuntu系统吧，oracal liunx系统不行
