### ISSUE TITLE
[feature]默认安装时为https

### ISSUE THREAD

**Issue by missdiog** [sprov065/v2-ui#49]
**描述你想要的功能**
v2-ui默认安装后为https，可以选用不可信证书。

**为何需要此功能**

确保页面内容安全。
**其它说明**

**Comment by sprov065** [comment]
不是所有人都有域名，你可以在访问面板前使用nginx反向https代理

**Comment by missdiog** [comment]
使用https 不一定用域名，用IP也可以。
