### ISSUE TITLE
安装之后就不能使用

### ISSUE THREAD

**Issue by songjian0** [sprov065/v2-ui#51]
安装上之后v2ray 不能使用。重新添加一个账号也是用不了

**Comment by JosephNew** [comment]
同样的问题出现了，这边通过放行端口确实能够进去面板了，但是账号加到客户端是不能用的，尝试用最新的v2rayN客户端仍然不能用，PAC和全局也不能用。
centos 7.6 from vultr
老版本的那个叫啥着，好像叫vpor-ui能用

**Comment by JosephNew** [comment]
试了一下，似乎每次添加一个节点，也都要再单独把这个节点的端口放行，这个步骤虽然合理，但是一方面原来老版不需要，另一方面其实脚本里面完全可以集成，也确实很不方便

**Comment by rayle2** [comment]
我也刚安装完面板，v2ray本地就不能使用了，请问如何解决

**Comment by yuanzzi** [comment]
> 试了一下，似乎每次添加一个节点，也都要再单独把这个节点的端口放行，这个步骤虽然合理，但是一方面原来老版不需要，另一方面其实脚本里面完全可以集成，也确实很不方便

你好，是指防火墙放行吗，我的还是不行呀

**Comment by sprov065** [comment]
端口放行这种事是自己应该要做的，面板不会去干扰用户的端口管理

**Comment by yuanzzi** [comment]
> 端口放行这种事是自己应该要做的，面板不会去干扰用户的端口管理

可是端口确认是开放的，安装过程也没报错，新建账号也还是不能用，一直500错误
