### ISSUE TITLE
[feature]账号界面能收缩展开

### ISSUE THREAD

**Issue by tozehu** [sprov065/v2-ui#52]
**描述你想要的功能**
账号界面可以收缩隐藏详细

**为何需要此功能**
账号太多了

**其它说明**
感谢作者

**Comment by sprov065** [comment]
本面板的初心是单服务器少量用户，搜索功能已经有了，这已经是最大的妥协了

**Comment by cracksfuck** [comment]
加上账号数量编号也好呀
