### ISSUE TITLE
[BUG]采用ws+tls，账号添加伪装地址后，二维码和连接都不能出现

### ISSUE THREAD

**Issue by linGinc** [sprov065/v2-ui#54]
1.使用ws+tls设置账号，并且正确填入信息及伪装域名
2.用win的v2rayN或者安卓kitsunebi扫码后，发现节点配置中，伪装地址是空的，没有填入的域名
3.设置多个ws+tls账号，时能连接上，有时无法连接（IP没有被封）

**Comment by sprov065** [comment]
没有必要设置伪装域名，真要设置也是去设置ws请求头中的Host，这个面板没有提供。

至于第3点跟你的网络状况有直接联系，跟面板毫无关系，面板只是一个配置工具。
