### ISSUE TITLE
希望可以自定义accounts的IP地址为域名

### ISSUE THREAD

**Issue by johnnyzhangcd** [sprov065/v2-ui#58]
![image](https://user-images.githubusercontent.com/47234845/64862211-83557400-d664-11e9-982c-a23b9b228386.png)
动态地址的家宽，希望可以自定义服务器为域名

**Comment by Warlock1994** [comment]
这个貌似是支持的吧，只要绑定了域名，自己会选择域名

**Comment by sprov065** [comment]
使用域名访问面板

**Comment by johnnyzhangcd** [comment]
> 这个貌似是支持的吧，只要绑定了域名，自己会选择域名

感谢

**Comment by johnnyzhangcd** [comment]
> 使用域名访问面板

这个方法可以
