### ISSUE TITLE
[feature]建议添加http/2的配置支持

### ISSUE THREAD

**Issue by syuraking** [sprov065/v2-ui#62]
既然有了WS+TLS，也希望用加入http/2了，毕竟这个无需要去配置nginx/caddy/apache了。

谢谢

**Comment by sprov065** [comment]
这个功能从第一个版本就有了，麻烦安装个面板仔细看一看

**Comment by syuraking** [comment]
唉，怪自己瞎眼或者智商问题了，http+ssl不就是h2么……
不好意思，解决

**Comment by yrong** [comment]
加个证书就变h2了?文盲

**Comment by cybmp3** [comment]
是HTTP+tls还是HTTP2+TLS啊=，=
