### ISSUE TITLE
无法通过域名只能通过IP访问web-ui

### ISSUE THREAD

**Issue by shoushi01** [sprov065/v2-ui#64]
三台服务器，两台正常。最后一台无法通过域名访问web-ui（centos 7全新安装，重启无效，yum update无效，http或https均无效，翻墙无效，测试过域名可以正常解析，可以通过域名使用v2ray），可以顺利载入登录标题，但是页面全空白。直接通过IP可以顺利访问web-ui。

**Comment by sprov065** [comment]
清除浏览器缓存再重试

**Comment by shoushi01** [comment]
> 清除浏览器缓存再重试

两台电脑，两套独立网络，均无效。

**Comment by shoushi01** [comment]
> 清除浏览器缓存再重试

火狐的Network工具显示最后一步停在了https://cdn.jsdelivr.net/npm/ant-design-vue@1.3.10/dist/antd.min.js
这部分内容不太熟悉

**Comment by shoushi01** [comment]
问题已解决。是被浏览器的广告过滤功能拦截了某个关键的模块导致页面无法显示。
