### ISSUE TITLE
[BUG]V2RAY账户与SS账户无法共存

### ISSUE THREAD

**Issue by shoushi01** [sprov065/v2-ui#65]
# 提问须知
 - 先仔细阅读博客文章及评论，查看是否有相关问题和解决方案，再查看所有 issues，包括已开启的和已关闭的，确认没有任何地方可以解决你的问题时再提问。
 - 如果需要上传图片，直接将图片拖入此文本框即可。
 - 提问的艺术：https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md

**描述你的问题**
>通过web-ui，可以添加一个v2ray（http+tls模式）账号，但是无法同时与SS账号共存。创建SS账号后，v2ray主程序无法正常启动；手动ssh重启v2ray服务后，SS账号可以连接但是V2RAY账户无法连接。需要将SS账户禁用后V2RAY账户可以自动恢复。在本机可复现。

**面板是否正常运行**
>提示：systemctl status v2-ui -l

**与问题相关的面板日志及其他内容**
>提示：cat /etc/v2-ui/v2-ui.log

**你所使用的面板版本**
4.6.0

**你所使用的系统（服务器）**
centos 7

**你所使用的浏览器**

**你猜测可能的原因**
猜测为生成的json配置文件出现异常。

**Comment by sprov065** [comment]
自行确保端口没有冲突，生成的 ss 配置一般不会出错，除非你自己修改错误。

如果端口确定没有冲突，请提供**出错时**和**未出错时**的完整 v2ray 配置文件，自行隐藏敏感信息。
