### ISSUE TITLE
[feature]建议增加动态端口功能

### ISSUE THREAD

**Issue by kalarita** [sprov065/v2-ui#66]
**提问须知**
在此统一说明一下，面板只是一个方便你配置 v2ray 的工具，v2ray 没有的功能面板也没有办法去配置，比如有人问我 ss 能不能加个混淆、能不能限制设备数/网速等等，这些功能 v2ray 是没有的。
我不是 v2ray 作者，这些核心的功能你得去找 v2ray，只有 v2ray 有了面板才能进行配置，链接在此：https://github.com/v2ray/v2ray-core/issues。

**描述你想要的功能**
动态端口

**为何需要此功能**
今天用kcp并进行utp伪装时端口被封，换了个端口就能用了

**其它说明**
无

**Comment by sprov065** [comment]
动态端口并不能解决你这个问题，反而会更容易造成你的 IP 挂掉，我也不建议使用动态端口。建议使用纯 tcp 或者 ws + tls、http/2 + tls

**Comment by kalarita** [comment]
> 动态端口并不能解决你这个问题，反而会更容易造成你的 IP 挂掉，我也不建议使用动态端口。建议使用纯 tcp 或者 ws + tls、http/2 + tls

刚注册好域名打算用ws+tls结果全面屏蔽了....

**Comment by 0x0004** [comment]
> > 动态端口并不能解决你这个问题，反而会更容易造成你的 IP 挂掉，我也不建议使用动态端口。建议使用纯 tcp 或者 ws + tls、http/2 + tls
> 
> 刚注册好域名打算用ws+tls结果全面屏蔽了....

全面屏蔽什么意思？

**Comment by kalarita** [comment]
vultr几乎新开的ip都挂了，没办法最后只能换了一家

0x0004 <notifications@github.com> 于 2019年9月21日周六 22:07写道：

**Comment by 0x0004** [comment]
> vultr

开vultr活该会挂啊，是哒叫得上名的厂商应该避着才对

**Comment by danerlt** [comment]
vultr 可以重新部署，有小概率能获取的一个可以使用的IP
