### ISSUE TITLE
能否加入多账号流量控制功能?

### ISSUE THREAD

**Issue by amColinzzz** [sprov065/v2-ui#7]
现在v2ray官方api只能统计流量,但是做不到流量控制,希望作者可以在面板中加入以下特别实用的功能:

- 多账号流量统计(已有)

- 每个账号单独分配流量上限配额

- 每个账号可进行单独限速
有了这些功能,就可以和别人一起共享了,不然其实很多流量都浪费了,共享给别人,又怕别人借出去,或者大流量传输.

**Comment by sprov065** [comment]
请自行找机场面板

**Comment by amColinzzz** [comment]
> 请自行找机场面板

您的意思是别用您的面板?用别人的?

**Comment by jiejie2004** [comment]
楼主改用sspanel v3 mod吧，有你需要的功能。mod在githun上有的。

**Comment by dlan17** [comment]
Hi，不想新开一个issue了，就在这问吧。。

能否实现 “每个账号单独分配流量上限配额”这个功能呢？

因为，目前的面板已经支持 1）流量统计了（能获取每个账号的流量），2）而且也可以禁止/停掉某个账号，两者想结合其实就能够做到“流量上限配额”的功能了（想象一下等于手动完成这个功能）

**Comment by pscj** [comment]
> Hi，不想新开一个issue了，就在这问吧。。
> 
> 能否实现 “每个账号单独分配流量上限配额”这个功能呢？
> 
> 因为，目前的面板已经支持 1）流量统计了（能获取每个账号的流量），2）而且也可以禁止/停掉某个账号，两者想结合其实就能够做到“流量上限配额”的功能了（想象一下等于手动完成这个功能）

顶你，同求此功能
