### ISSUE TITLE
[feature]端口复用

### ISSUE THREAD

**Issue by Googleing** [sprov065/v2-ui#70]
**提问须知**
在此统一说明一下，面板只是一个方便你配置 v2ray 的工具，v2ray 没有的功能面板也没有办法去配置，比如有人问我 ss 能不能加个混淆、能不能限制设备数/网速等等，这些功能 v2ray 是没有的。
我不是 v2ray 作者，这些核心的功能你得去找 v2ray，只有 v2ray 有了面板才能进行配置，链接在此：https://github.com/v2ray/v2ray-core/issues。

**描述你想要的功能**
端口复用

**为何需要此功能**
目前一个端口只能给一个用户，使用 websocket + cdn 的情况下端口支持数量是有限的（如 cloudflare 只提供8个左右） ，而多人使用同一用户又不具备安全性，也不能统计各自的流量

**Comment by sprov065** [comment]
重复问题，https://github.com/sprov065/v2-ui/issues/46
