### ISSUE TITLE
希望能增加docker的支持，读取v2ray api的时候把ip也读出来

### ISSUE THREAD

**Issue by kevinconan** [sprov065/v2-ui#71]
看到生成v2ray api命令的代码里面只从模板json里面读取了api端口，没有读取ip，ip默认是127.0.0.1.这个对docker不大友好啊，希望可以直接读取ip，这样面板就能过通过docker link访问独立容器中跑的v2ray了。本人没玩儿过Py，就不提PR了.

**Comment by sprov065** [comment]
可以安排
