### ISSUE TITLE
[BUG]添加多个账号，发现服务器配置文件中第二个账号uid记录错误

### ISSUE THREAD

**Issue by erich50888** [sprov065/v2-ui#72]
面板4.6
时间：2019/9/20
第一个账号直接默认选项创建
第二个自主选项ws+tls，发现不能连接，检查服务器配置文件时，发现第二个账号配置文件中uid记录与账号内记录不一致

**Comment by sprov065** [comment]
添加账号后 60 秒内配置才会生成并生效
