### ISSUE TITLE
[BUG]v2ray 状态：错误

### ISSUE THREAD

**Issue by 136478738** [sprov065/v2-ui#74]
v2ray 状态：错误

**Comment by 136478738** [comment]
v2-ui.service - v2-ui Service
   Loaded: loaded (/etc/systemd/system/v2-ui.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2019-09-20 23:39:35 CST; 5min ago
 Main PID: 1949 (v2-ui)
   CGroup: /system.slice/v2-ui.service
           ├─1949 /usr/local/v2-ui/v2-ui
           └─1950 /usr/local/v2-ui/v2-ui

**Comment by wang81732532** [comment]
同样的问题，而且账户列表里面流量不显示了系统是ubuntu18.04

**Comment by sprov065** [comment]
下个版本修复

**Comment by skyloveyu** [comment]
@sprov065 When is the next version expected?

**Comment by ventusyu** [comment]
请问修复了吗？
