### ISSUE TITLE
[BUG]正确安装面板，显示65432端口listen，外网显示65432端口可用，但是外网（美西）无法ping通，也无法打开ip+65432端口的面板，firewall和iptables已经全部完全卸载关闭

### ISSUE THREAD

**Issue by CloudWzhZzz** [sprov065/v2-ui#76]
**描述你的问题**
正确安装面板，显示65432端口listen，外网显示65432端口可用，但是外网（美西）无法ping通，也无法打开ip+65432端口的面板，firewall和iptables已经全部完全卸载关闭

**面板是否正常运行**
显示正常运行running

**你所使用的面板版本**
最新版

**你所使用的系统（服务器）**
cenos7*64

**你所使用的浏览器**
chorme最新版

**你猜测可能的原因**
无解

**Comment by fuzhengqu** [comment]
我这更奇怪了，外网IP一直可以ping通，服务器可以登录，面板可以打开，建立了不同协议的账户好多个，每一个能连上的。Google cloud、Microsoft Azure都试过了，不同地区的，每一个行的。不知道是不是最近这个时间点的问题

**Comment by CloudWzhZzz** [comment]
我这边排除防火墙的问题，端口打开、服务启动显示listen状态，但是就是打不开面板。

**Comment by Vhibli** [comment]
我在centos7上一切正常，只不过每配置一个账号都要手动放行端口。这是要把防火墙整个关掉吗？我以为添加好账号后端口也顺便放行了啊

**Comment by Vhibli** [comment]
> **描述你的问题**
> 正确安装面板，显示65432端口listen，外网显示65432端口可用，但是外网（美西）无法ping通，也无法打开ip+65432端口的面板，firewall和iptables已经全部完全卸载关闭
> 
> **面板是否正常运行**
> 显示正常运行running
> 
> **你所使用的面板版本**
> 最新版
> 
> **你所使用的系统（服务器）**
> cenos7*64
> 
> **你所使用的浏览器**
> chorme最新版
> 
> **你猜测可能的原因**
> 无解
chrome自动使用https去访问了，默认443，当然访问不到，我在mac上用safari访问ip+端口一切正常。不知道你那边是不是这个问题

**Comment by CloudWzhZzz** [comment]
> 我在centos7上一切正常，只不过每配置一个账号都要手动放行端口。这是要把防火墙整个关掉吗？我以为添加好账号后端口也顺便放行了啊

我直接把firewalld和iptables全部卸载了，肯定没有任何阻挡了哇

**Comment by CloudWzhZzz** [comment]
> > **描述你的问题**
> > 正确安装面板，显示65432端口listen，外网显示65432端口可用，但是外网（美西）无法ping通，也无法打开ip+65432端口的面板，firewall和iptables已经全部完全卸载关闭
> > **面板是否正常运行**
> > 显示正常运行running
> > **你所使用的面板版本**
> > 最新版
> > **你所使用的系统（服务器）**
> > cenos7*64
> > **你所使用的浏览器**
> > chorme最新版
> > **你猜测可能的原因**
> > 无解
> > chrome自动使用https去访问了，默认443，当然访问不到，我在mac上用safari访问ip+端口一切正常。不知道你那边是不是这个问题

那我试一下哈。

**Comment by Vhibli** [comment]
> > 我在centos7上一切正常，只不过每配置一个账号都要手动放行端口。这是要把防火墙整个关掉吗？我以为添加好账号后端口也顺便放行了啊
> 
> 我直接把firewalld和iptables全部卸载了，肯定没有任何阻挡了哇

不用卸载的，你要是部署在centos7 。放行端口加reload就行了啊。比如：

开放8080端口
firewall-cmd --permanent --add-port=8080/tcp
firewall-cmd --reload

**Comment by CloudWzhZzz** [comment]
> > > 我在centos7上一切正常，只不过每配置一个账号都要手动放行端口。这是要把防火墙整个关掉吗？我以为添加好账号后端口也顺便放行了啊
> > 
> > 
> > 我直接把firewalld和iptables全部卸载了，肯定没有任何阻挡了哇
> 
> 不用卸载的，你要是部署在centos7 。放行端口加reload就行了啊。比如：
> 
> 开放8080端口
> firewall-cmd --permanent --add-port=8080/tcp
> firewall-cmd --reload

好的，谢谢~因为我一直打不开，所以用了完全卸载的办法来排除防火墙，我现在已经按照你得方法逐个放通端口了~谢谢啦~
