### ISSUE TITLE
[feature]给开发人员的环境配置说明

### ISSUE THREAD

**Issue by 690933449** [sprov065/v2-ui#77]
**提问须知**
在此统一说明一下，面板只是一个方便你配置 v2ray 的工具，v2ray 没有的功能面板也没有办法去配置，比如有人问我 ss 能不能加个混淆、能不能限制设备数/网速等等，这些功能 v2ray 是没有的。
我不是 v2ray 作者，这些核心的功能你得去找 v2ray，只有 v2ray 有了面板才能进行配置，链接在此：https://github.com/v2ray/v2ray-core/issues。

**描述你想要的功能**
想要一个开发人员的环境配置说明。

**为何需要此功能**
项目中有用到许多的第三方库和包，希望能够有一个开发环境配置的说明，从而能够更好地完善这个项目。

**其它说明**

**Comment by sprov065** [comment]
之后添上 requirements.txt
