### ISSUE TITLE
[BUG]系统状态显示 CPU 持续 100%

### ISSUE THREAD

**Issue by yuangezhizao** [sprov065/v2-ui#78]
**描述你的问题**
系统状态显示 CPU 持续 100%

**面板是否正常运行**
>● v2-ui.service - v2-ui Service
   Loaded: loaded (/etc/systemd/system/v2-ui.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2019-09-24 23:46:09 CST; 4min 29s ago
 Main PID: 18100 (v2-ui)
   CGroup: /system.slice/v2-ui.service
           ├─18100 /usr/local/v2-ui/v2-ui
           └─18102 /usr/local/v2-ui/v2-ui

Sep 24 23:46:09 CentOS systemd[1]: Stopped v2-ui Service.
Sep 24 23:46:09 CentOS systemd[1]: Started v2-ui Service.

**与问题相关的面板日志及其他内容**
> 2019-09-24 23:46:02-root-WARNING-Failed to get system status information: float division by zero

**你所使用的面板版本**
4.7.0

**你所使用的系统（服务器）**
CentOS Linux release 7.6.1810 (Core) 

**你所使用的浏览器**
CentBrowser

**你猜测可能的原因**
计算出错，被零除？？？

**Comment by yuangezhizao** [comment]
![有时还会出现一个js 报错](https://user-images.githubusercontent.com/16861681/65528227-8d118e00-df26-11e9-8b45-b189860f7457.png)

**Comment by sprov065** [comment]
服务器是 lightsail 的?

可能是由于服务器 st 占用高，导致 CPU 处理不及时面板的运行导致的。至于前端 js 报错是后端这个问题引起的，多刷新几次页面即可。

下个版本修复。

**Comment by yuangezhizao** [comment]
服务器是 Skysilk 的最低配，然后贴两张状态图
![1](https://user-images.githubusercontent.com/16861681/65704767-b4e52b00-e0b9-11e9-8a2d-11f79e2fefc0.png)
![2](https://user-images.githubusercontent.com/16861681/65704805-c75f6480-e0b9-11e9-8886-9f9c732167ea.png)

还有 st 指的是？感谢修复

**Comment by sprov065** [comment]
大兄弟，你这个 v2ray 占 CPU 跟我面板有啥关系。。。要么是你服务器用的人太多了，要么是你服务器的 CPU 确实差或者商家超售严重，用个 v2ray 也卡

**Comment by yuangezhizao** [comment]
哭笑（服务器性能确实辣鸡，毕竟白嫖

奇怪商家统计的 CPU 并没有到 100%，但是 htop 看到的占用却较高（之前以为面板 CPU 100% 是计算错误呢……

还有 `还有 st 指的是？`
