### ISSUE TITLE
[feature]希望可以有一个v2-ui的docker

### ISSUE THREAD

**Issue by meHobby** [sprov065/v2-ui#79]
**提问须知**
在此统一说明一下，面板只是一个方便你配置 v2ray 的工具，v2ray 没有的功能面板也没有办法去配置，比如有人问我 ss 能不能加个混淆、能不能限制设备数/网速等等，这些功能 v2ray 是没有的。
我不是 v2ray 作者，这些核心的功能你得去找 v2ray，只有 v2ray 有了面板才能进行配置，链接在此：https://github.com/v2ray/v2ray-core/issues。
**描述你想要的功能**
希望可以在Docker Hub添加一个官方的镜像，可以快速布置v2ray和v2-ui面板。

**为何需要此功能**
群晖上用docker来创建最简单，也比较适合小白，相信对于大大来说也只是写个脚本这么简单的事情而已，感谢大佬。

**其它说明**

**Comment by sprov065** [comment]
目前的面板不适合docker，如果你有好的解决方式可以提供建议或贡献代码

**Comment by LoliVPN** [comment]
#99
