### ISSUE TITLE
[feature]希望可以修改每个账户的加密算法

### ISSUE THREAD

**Issue by gavinyueng** [sprov065/v2-ui#80]
因为我想给每个不同设备添加一个账号，但移动设备更适合chacha20，电脑更适合其他加密算法，所以希望能在面板中直接修改加密算法的类型。感谢作者！

**Comment by sprov065** [comment]
![image](https://user-images.githubusercontent.com/47310637/65815585-13c6b380-e224-11e9-95dc-88ae156180e5.png)
v2ray 服务端本身就不能也不需要指定加密方式，你客户端选择什么加密就是什么加密
