### ISSUE TITLE
aws安装最新版显示状态错误，客户端无法连接

### ISSUE THREAD

**Issue by Omoinemie** [sprov065/v2-ui#81]
开了个aws服务器，装了个bbr，直接装v2-ui，创建账号后显示状态错误，客户端也无法连接

**Comment by sprov065** [comment]
请提供更多详细信息

**Comment by syuraking** [comment]
AWS没有任何问题，已经安装测试通过

**Comment by Omoinemie** [comment]
网页错误日志

**Comment by Omoinemie** [comment]
Failed to load resource: the server responded with a status of 404 (NOT FOUND)
