### ISSUE TITLE
WS+TLS只能是单用户使用？

### ISSUE THREAD

**Issue by zhtyirg3** [sprov065/v2-ui#82]
你好，我跟着教程弄好了WS+tls, 已经可以用。但是有一个问题想请教一下，我去官网看V2RAY一个用户只能支持一个设备，我用V2-UI脚本，在面板上开了多个用户，一个用户使用了WS+TLS之后，我发现，其他用户只要是输入443端口按保存，就显示网络错误，这是什么原因？其他用户是不是不能用同一个域名和端口443？我的本意是想每个用户都配置WS+TLS（同一个域名），现在用不了443端口，用其他什么端口比较合适呢？

**Comment by sprov065** [comment]
不支持单端口多用户配置，请配置其它端口，用哪个端口都行

**Comment by UVJkiNTQ** [comment]
> 不支持单端口多用户配置，请配置其它端口，用哪个端口都行

是否考虑支持localhost的单端口多用户？这样在一个配置文件内多client解决就不会存在端口冲突了。

**Comment by minitru1014** [comment]
一个端口相同配置可以设置的吧 只是uuid'不同？

**Comment by colemanlee** [comment]
> 不支持单端口多用户配置，请配置其它端口，用哪个端口都行

地址使用`域名:443`能正常使用，但是多用户使用其他端口如`域名:25876`就无法连接使用了。是不是CDN保护只能保护80和443端口，多用户时就无法使用CDN了？

**Comment by ebisuxx** [comment]
事实上
