### ISSUE TITLE
[feature]如何配置caddy反向代理来用网址访问面板

### ISSUE THREAD

**Issue by novicewu** [sprov065/v2-ui#84]
**描述你想要的功能**
想要通过caddy设置反向代理, 达到用网址直接访问面板的目的. 比如 example.com/v2-ui, 而不是ip:65432

**为何需要此功能**
方便, 简介

**其它说明**
按照博客建议的nginx的设置方法, 将根目录设置成/v2-ui, 在caddy里设置如下

example.com/v2-ui {
  proxy / localhost:65432
}

但是在网址里输入example.com/v2-ui的时候, 会直接跳转成 localhost:65432/v2ray, 导致无法访问.

请大神帮忙解决.

<img width="191" alt="Screen Shot 2019-09-30 at 08 09 47" src="https://user-images.githubusercontent.com/8786994/65841903-fa278800-e359-11e9-9983-1f261c6d5360.png">

<img width="340" alt="Screen Shot 2019-09-30 at 08 09 58" src="https://user-images.githubusercontent.com/8786994/65841887-c3517200-e359-11e9-8704-dc0c21ec4201.png">

**Comment by sprov065** [comment]
其它软件配置问题请自行研究

**Comment by magicalz** [comment]
caddy我是这么配的
your-domain{      
  proxy /v2ui localhost:9999/v2ui {
          header_upstream X-Forwarded-Host {host}
          header_upstream -Origin
          header_upstream -Referer
          without /v2ui
          }
}
我的v2ray也是用caddy反代的，域名套了CDN，目前都正常运行

PS：这个ui面板很不错，只是希望后续版本能够支持多用户单端口，因为这是v2ray本身支持的功能，真的没必要多开端口来着

**Comment by novicewu** [comment]
> caddy我是这么配的
> your-domain{
> proxy /v2ui localhost:9999/v2ui {
> header_upstream X-Forwarded-Host {host}
> header_upstream -Origin
> header_upstream -Referer
> without /v2ui
> }
> }
> 我的v2ray也是用caddy反代的，域名套了CDN，目前都正常运行
> 
> PS：这个ui面板很不错，只是希望后续版本能够支持多用户单端口，因为这是v2ray本身支持的功能，真的没必要多开端口来着

配置v2ray我没有问题. 我是要配置网页访问控制面板不知道怎么设置.

**Comment by magicalz** [comment]
caddy我是这么配的
your-domain{      
  proxy /v2ui localhost:9999/v2ui {
          header_upstream X-Forwarded-Host {host}
          header_upstream -Origin
          header_upstream -Referer
          without /v2ui
          }
}
我的v2ray也是用caddy反代的，域名套了CDN，目前都正常运行

PS：这个ui面板很不错，只是希望后续版本能够支持多用户单端口，因为这是v2ray本身支持的功能，真的没必要多开端口来着

> 
> 
> > caddy我是这么配的
> > your-domain{
> > proxy /v2ui localhost:9999/v2ui {
> > header_upstream X-Forwarded-Host {host}
> > header_upstream -Origin
> > header_upstream -Referer
> > without /v2ui
> > }
> > }
> > 我的v2ray也是用caddy反代的，域名套了CDN，目前都正常运行
> > PS：这个ui面板很不错，只是希望后续版本能够支持多用户单端口，因为这是v2ray本身支持的功能，真的没必要多开端口来着
> 
> 配置v2ray我没有问题. 我是要配置网页访问控制面板不知道怎么设置.

上面的就是v2-ui的caddy反代配置

**Comment by magicalz** [comment]
我发的就是v2-ui的caddy反代配置

**Comment by magicalz** [comment]
我发的就是v2-ui的caddy反代配置，请自行更改你的域名，端口号和baseurl

**Comment by magicalz** [comment]
我发的就是v2-ui的caddy反代配置，请自行更改你的域名，端口号和baseurl

**Comment by xianshenglu** [comment]
我用 nginx 弄好了，你可以 [看下](https://github.com/xianshenglu/crossTheWall/blob/master/v2ray/v2ray-nginx.md)，可能有帮助

**Comment by novicewu** [comment]
感谢各位的回复. 试了一下楼上两位的方法, 还是无法实现. 最后通过查找资料解决 (加入一行transparent). 希望对与我遇到一样问题的人有帮助.

your-domain {
  proxy / localhost:65432 {
    transparent
  }
}

**Comment by swotom** [comment]
> 感谢各位的回复. 试了一下楼上两位的方法, 还是无法实现. 最后通过查找资料解决 (加入一行transparent). 希望对与我遇到一样问题的人有帮助.
> 
> your-domain {
> proxy / localhost:65432 {
> transparent
> }
> }

亲测这个和楼上那个都是好用的配置，另外需要提醒下，需要在v2-ui面板设置中删除证书和密钥设置，我因为之前在面板中配置了证书和密钥，一直404或者502，最后删了才好。
