### ISSUE TITLE
[feature]请问是用什么工具打包的

### ISSUE THREAD

**Issue by deluxebear** [sprov065/v2-ui#85]
请问作者，此项目发布的包是用什么工具打的，想学习一下。

**Comment by sprov065** [comment]
pyinstaller，这个问题老早就有人问过

**Comment by 690933449** [comment]
> pyinstaller，这个问题老早就有人问过

#29 这个吧，我觉得这一项可以写在readme里，我也是找了半天才想到去关闭的issue里找

**Comment by kqkq** [comment]
同样希望把pyinstaller打包的步骤写到README里，把相关脚本也加到版本库中

**Comment by 690933449** [comment]
@kqkq 其实就两行命令，参考我fork的 [v2-ui](https://github.com/690933449/v2-ui#%E9%A1%B9%E7%9B%AE%E6%89%93%E5%8C%85) ，再就是 `.spec` 里的 `datas` 的修改

**Comment by unkosun** [comment]
@690933449 你fork的项目中，可以增加开发环境的配置吗？

**Comment by 690933449** [comment]
@unkosun 好，后面还会有个版本的更新，在后面会加上的
