### ISSUE TITLE
[BUG]面板设置进不去

### ISSUE THREAD

**Issue by Promix953** [sprov065/v2-ui#86]
**描述你的问题**
>其他功能都正常，但是面板设置进不去，浏览器一直加载/v2ray/setting/，页面显示空白，已尝试各种重置，无效

**面板是否正常运行**
>正常运行

**与问题相关的面板日志及其他内容**
>日志空白

**你所使用的面板版本**
v4.7.0

**你所使用的系统（服务器）**
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.11 (jessie)
Release:	8.11
Codename:	jessie

**你所使用的浏览器**
Chrome 77.0.3865.90（正式版本） （64 位）

**你猜测可能的原因**
看不到任何日志输出，无法推测

**Comment by sprov065** [comment]
按F12，查看console的错误信息与network的请求信息
