### ISSUE TITLE
树莓派4b 安装不了v2-ui面板

### ISSUE THREAD

**Issue by wangkai88** [sprov065/v2-ui#88]
v2-ui在树莓派4b 安装原版的官方系统 Raspbian上安装不了

**Comment by sprov065** [comment]
不支持

**Comment by wangkai88** [comment]
v2ray 可以安装到debian系统上面，只是你的一键安装脚本，没有适配兼容，

https://raw.githubusercontent.com/ColetteContreras/v2ray-ssrpanel-plugin/master/install-release.sh
这里有兼容处理器和系统的安装脚本
