### ISSUE TITLE
[BUG] 换成mysql数据库的时候，报错

### ISSUE THREAD

**Issue by iotmu** [sprov065/v2-ui#90]
**描述你的问题**
数据库配置换成mysql的时候， 运行报错 sqlalchemy.exc.CompileError: (in table 'inbound', column 'settings'): VARCHAR requires a length on dialect mysql
 
如果使用mysql数据库，String类型对应的是VARCHAR类型，需要指定长度，否则会报下面错误，而在sqlite不会出现
能不能判断一下或者兼容一下mysql的配置

**Comment by sprov065** [comment]
面板已经自带小型数据库了，没有必要再去支持其它数据库。你既然会修改连接数据库的配置，那么这个问题对你来说也不是难事。
