### ISSUE TITLE
[BUG]配置证书绝对路径无法通过

### ISSUE THREAD

**Issue by daohes** [sprov065/v2-ui#92]
2019-10-06 11:29:54-asyncio-ERROR-Exception in callback BaseAsyncIOLoop._handle_events(5, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(5, 1)>
Traceback (most recent call last):
  File "asyncio/events.py", line 145, in _run
  File "tornado/platform/asyncio.py", line 138, in _handle_events
  File "tornado/netutil.py", line 273, in accept_handler
  File "tornado/tcpserver.py", line 288, in _handle_connection
  File "tornado/netutil.py", line 605, in ssl_wrap_socket
  File "tornado/netutil.py", line 574, in ssl_options_to_context
IsADirectoryError: [Errno 21] Is a directory

**Comment by sprov065** [comment]
文件和目录都弄不清楚吗

**Comment by daohes** [comment]
![image](https://user-images.githubusercontent.com/32756278/66449847-0e216700-ea89-11e9-87aa-4de6c2d2cc71.png)
这样应该怎么填呢，已经试过各种了都不行。

**Comment by daohes** [comment]
/ico.site_chain,crt 这样写不对吗？
还是/
这两种方法都试过了，无解。

**Comment by wangyinglei0912** [comment]
> 
> 
> /ico.site_chain,crt 这样写不对吗？
> 还是/
> 这两种方法都试过了，无解。

请问最后解决了吗？具体应该怎么写证书的绝对路径呢

**Comment by daohes** [comment]
> > /ico.site_chain,crt 这样写不对吗？
> > 还是/
> > 这两种方法都试过了，无解。
> 
> 请问最后解决了吗？具体应该怎么写证书的绝对路径呢

没有，我还在想是不是文件传输失败了，或者是权限不够，但都试过了都不行。你也是遇到这个问题了吗？ 😭 😭 😭 😭

**Comment by wangyinglei0912** [comment]
> > > /ico.site_chain,crt 这样写不对吗？
> > > 还是/
> > > 这两种方法都试过了，无解。
> > 
> > 
> > 请问最后解决了吗？具体应该怎么写证书的绝对路径呢
> 
> 没有，我还在想是不是文件传输失败了，或者是权限不够，但都试过了都不行。你也是遇到这个问题了吗？ 😭 😭 😭 😭

我的解决了，参考问题94  https://github.com/sprov065/v2-ui/issues/94

**Comment by liby** [comment]
@wangyinglei0912 
想问一下,你证书配置成功以后, 原来的ip:65432 这个地址还能访问吗

**Comment by daohes** [comment]
> @daohes
> 我的不行,我是使用cloundflare解析的DNS,我查了一下他开发的https端口中有2096,我就把面板端口设置成这个,结果ip:2096也打不开, [https://域名:2096也打不开](https://%E5%9F%9F%E5%90%8D:2096%E4%B9%9F%E6%89%93%E4%B8%8D%E5%BC%80)

你有没有打开65432这个端口哦？

firewall-cmd --zone=public --list-ports

用上面命令查看下有没有打开65432端口吧。

**Comment by liby** [comment]
@daohes 
我认为当时是DNS解析的问题，我现在还是改用手动配置了，免除这些issue了

**Comment by daohes** [comment]
> @daohes
> 我认为当时是DNS解析的问题，我现在还是改用手动配置了，免除这些issue了， 谢谢你

私以为v2ray有更好的多用户配置方式，我也没用这个（小声BB），因为出来各种issues，哈哈。😭
