### ISSUE TITLE
[feature]在此填写一个标题

### ISSUE THREAD

**Issue by kimanlo** [sprov065/v2-ui#93]
作者，你好。
v2-ui 面板添加的帐号，配置文件中 Inbounds tag 默认 tag-端口号 的格式，可否添加一个功能可以自定义呢？
还有问题请教：
1、是不是每次重启  v2-ui，上述所说的修改会恢复默认格式？
2、默认的 tag 是不是用作统计流量之用？

**Comment by sprov065** [comment]
不可以自定义，怕有些小白不懂乱搞tag，出了问题又不会解决。
不能擅自修改v2ray配置文件，必须在面板设置里修改配置模板。
统计流量用。

最后的建议：既然用了v2-ui，那就按照v2-ui的规则来，使用inbound-端口号的方式来用tag。

**Comment by kimanlo** [comment]
感谢作者解答，自定义只不过方便自己去阅读，但是既然“既然用了v2-ui，那就按照v2-ui的规则来，使用inbound-端口号的方式来用tag”，这个问题也可以解决~
