### ISSUE TITLE
域名证书的问题

### ISSUE THREAD

**Issue by 2444989** [sprov065/v2-ui#94]
![(~4@{`Y@1)_GY6KN9R`DC2C](https://user-images.githubusercontent.com/56269715/66331557-71b27400-e965-11e9-913a-9a5f7822c556.png)
![L 5EO8{T4@ARL~Z%X@(6SJ](https://user-images.githubusercontent.com/56269715/66331814-f3a29d00-e965-11e9-96ce-14590f268a08.png)
![Y$ Q99G`YQ2$0SF8B1__Q$2](https://user-images.githubusercontent.com/56269715/66331925-2e0c3a00-e966-11e9-9f92-2bcd2f204861.png)
![@09~VK NH08UCLH71 V) (E](https://user-images.githubusercontent.com/56269715/66332072-73c90280-e966-11e9-98c6-72b5d5f28249.png)

**Comment by wangyinglei0912** [comment]
我也遇到同样问题，请问楼主解决了吗？

**Comment by sprov065** [comment]
配置证书后用https访问，用http访问那配置证书有何意义

**Comment by wangyinglei0912** [comment]
> 
> 
> 配置证书后用https访问，用http访问那配置证书有何意义

一语惊醒梦中人！！！
