### ISSUE TITLE
v2ray安装面板，苹果手机Shadowrocket-2.1.10翻不了。安卓手机和电脑都可以正常用

### ISSUE THREAD

**Issue by followme1213** [sprov065/v2-ui#95]
# 提问须知
 - 先仔细阅读博客文章及评论，查看是否有相关问题和解决方案，再查看所有 issues，包括已开启的和已关闭的，确认没有任何地方可以解决你的问题时再提问。
 - 如果需要上传图片，直接将图片拖入此文本框即可。
 - 提问的艺术：https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md

**描述你的问题**
>请尽可能的精确描述你的问题，尽量不要使用笼统的词汇。
v2ray安装面板，苹果手机Shadowrocket-2.1.10翻不了；我直接搭建v2ray，苹果手机Shadowrocket-2.1.10能翻墙。Shadowrocket-2.1.12版本也是苹果手机翻不了。
安卓手机和电脑，不管是面板还是直接搭建v2ray，都是正常能翻墙
**面板是否正常运行**
>提示：systemctl status v2-ui -l

面板是正常运行的

**与问题相关的面板日志及其他内容**
>提示：cat /etc/v2-ui/v2-ui.log

**你所使用的面板版本**
面板版本：4.7.0

**你所使用的系统（服务器）**
centos_7_06_64位

**你所使用的浏览器**
搜狗浏览器、谷歌浏览器、360浏览器

**你猜测可能的原因**
用面板搭建的V2ray和苹果手机上Shadowrocket有冲突。

**Comment by followme1213** [comment]
我同一台服务器上测试了，防火墙全部开放的。安装面板V2ray，苹果手机Shadowrocket翻不了。如果是直接搭建V2ray，苹果手机Shadowrocket可以翻墙。就是安装的方式不一样。2种方式：安卓手机和电脑都可以翻墙。

**Comment by Mtora** [comment]
> 我同一台服务器上测试了，防火墙全部开放的。安装面板V2ray，苹果手机Shadowrocket翻不了。如果是直接搭建V2ray，苹果手机Shadowrocket可以翻墙。就是安装的方式不一样。2种方式：安卓手机和电脑都可以翻墙。

用2.1.12可以，2.1.12增加了对v2ray的websocket的支持。

**Comment by followme1213** [comment]
> > 我同一台服务器上测试了，防火墙全部开放的。安装面板V2ray，苹果手机Shadowrocket翻不了。如果是直接搭建V2ray，苹果手机Shadowrocket可以翻墙。就是安装的方式不一样。2种方式：安卓手机和电脑都可以翻墙。
> 
> 用2.1.12可以，2.1.12增加了对v2ray的websocket的支持。

用2.1.12测试过，不行。

**Comment by sprov065** [comment]
其它软件的问题请找其它软件的开发者

**Comment by lidg080** [comment]
peer名称那里要写上对应的域名

**Comment by dsjasonh** [comment]
2.1.35亲测OK（最新的版本）
另外，如果你开启了TLS，记得在下火箭里面，把tls勾上，并且选择“允许不安全”
